version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: friday
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    cooldown:
      default-days: 5

  - package-ecosystem: npm
    directory: /cmd/explorer/frontend
    schedule:
      interval: weekly
      day: friday
    groups:
      npm-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    cooldown:
      default-days: 5
