// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSchema() {
  return window['go']['main']['App']['GetSchema']();
}

export function GetTypeDetails(arg1) {
  return window['go']['main']['App']['GetTypeDetails'](arg1);
}

export function RefreshSchema() {
  return window['go']['main']['App']['RefreshSchema']();
}
