// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {explorer} from '../models';

export function GetSchema():Promise<explorer.SchemaResponse>;

export function GetTypeDetails(arg1:string):Promise<explorer.SchemaType>;

export function RefreshSchema():Promise<void>;
