// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { explorer } from '../models';

export function GetSchema(): Promise<explorer.SchemaResponse>;

export function GetTypeDetails(arg1: string): Promise<explorer.SchemaType>;

export function RefreshSchema(): Promise<void>;

export function GetRandomNodes(arg1: number): Promise<explorer.GraphResponse>;

export function GetRelationships(arg1: string, arg2: number, arg3: number): Promise<explorer.RelationshipsResponse>;

export function GetNodeDetails(arg1: string): Promise<explorer.GraphNode>;

export function GetNodes(arg1: explorer.NodeFilter): Promise<explorer.GraphResponse>;
