// Code generated by ent, DO NOT EDIT.

package discoveredentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the discoveredentity type in the database.
	Label = "discovered_entity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUniqueID holds the string denoting the unique_id field in the database.
	FieldUniqueID = "unique_id"
	// FieldTypeCategory holds the string denoting the type_category field in the database.
	FieldTypeCategory = "type_category"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProperties holds the string denoting the properties field in the database.
	FieldProperties = "properties"
	// FieldEmbedding holds the string denoting the embedding field in the database.
	FieldEmbedding = "embedding"
	// FieldConfidenceScore holds the string denoting the confidence_score field in the database.
	FieldConfidenceScore = "confidence_score"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the discoveredentity in the database.
	Table = "discovered_entities"
)

// Columns holds all SQL columns for discoveredentity fields.
var Columns = []string{
	FieldID,
	FieldUniqueID,
	FieldTypeCategory,
	FieldName,
	FieldProperties,
	FieldEmbedding,
	FieldConfidenceScore,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UniqueIDValidator is a validator for the "unique_id" field. It is called by the builders before save.
	UniqueIDValidator func(string) error
	// TypeCategoryValidator is a validator for the "type_category" field. It is called by the builders before save.
	TypeCategoryValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultConfidenceScore holds the default value on creation for the "confidence_score" field.
	DefaultConfidenceScore float64
	// ConfidenceScoreValidator is a validator for the "confidence_score" field. It is called by the builders before save.
	ConfidenceScoreValidator func(float64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the DiscoveredEntity queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUniqueID orders the results by the unique_id field.
func ByUniqueID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUniqueID, opts...).ToFunc()
}

// ByTypeCategory orders the results by the type_category field.
func ByTypeCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTypeCategory, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByConfidenceScore orders the results by the confidence_score field.
func ByConfidenceScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidenceScore, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
