// Code generated by ent, DO NOT EDIT.

package discoveredentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Blogem/enron-graph/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLTE(FieldID, id))
}

// UniqueID applies equality check predicate on the "unique_id" field. It's identical to UniqueIDEQ.
func UniqueID(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldUniqueID, v))
}

// TypeCategory applies equality check predicate on the "type_category" field. It's identical to TypeCategoryEQ.
func TypeCategory(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldTypeCategory, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldName, v))
}

// ConfidenceScore applies equality check predicate on the "confidence_score" field. It's identical to ConfidenceScoreEQ.
func ConfidenceScore(v float64) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldConfidenceScore, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldCreatedAt, v))
}

// UniqueIDEQ applies the EQ predicate on the "unique_id" field.
func UniqueIDEQ(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldUniqueID, v))
}

// UniqueIDNEQ applies the NEQ predicate on the "unique_id" field.
func UniqueIDNEQ(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNEQ(FieldUniqueID, v))
}

// UniqueIDIn applies the In predicate on the "unique_id" field.
func UniqueIDIn(vs ...string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldIn(FieldUniqueID, vs...))
}

// UniqueIDNotIn applies the NotIn predicate on the "unique_id" field.
func UniqueIDNotIn(vs ...string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNotIn(FieldUniqueID, vs...))
}

// UniqueIDGT applies the GT predicate on the "unique_id" field.
func UniqueIDGT(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGT(FieldUniqueID, v))
}

// UniqueIDGTE applies the GTE predicate on the "unique_id" field.
func UniqueIDGTE(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGTE(FieldUniqueID, v))
}

// UniqueIDLT applies the LT predicate on the "unique_id" field.
func UniqueIDLT(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLT(FieldUniqueID, v))
}

// UniqueIDLTE applies the LTE predicate on the "unique_id" field.
func UniqueIDLTE(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLTE(FieldUniqueID, v))
}

// UniqueIDContains applies the Contains predicate on the "unique_id" field.
func UniqueIDContains(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldContains(FieldUniqueID, v))
}

// UniqueIDHasPrefix applies the HasPrefix predicate on the "unique_id" field.
func UniqueIDHasPrefix(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldHasPrefix(FieldUniqueID, v))
}

// UniqueIDHasSuffix applies the HasSuffix predicate on the "unique_id" field.
func UniqueIDHasSuffix(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldHasSuffix(FieldUniqueID, v))
}

// UniqueIDEqualFold applies the EqualFold predicate on the "unique_id" field.
func UniqueIDEqualFold(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEqualFold(FieldUniqueID, v))
}

// UniqueIDContainsFold applies the ContainsFold predicate on the "unique_id" field.
func UniqueIDContainsFold(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldContainsFold(FieldUniqueID, v))
}

// TypeCategoryEQ applies the EQ predicate on the "type_category" field.
func TypeCategoryEQ(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldTypeCategory, v))
}

// TypeCategoryNEQ applies the NEQ predicate on the "type_category" field.
func TypeCategoryNEQ(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNEQ(FieldTypeCategory, v))
}

// TypeCategoryIn applies the In predicate on the "type_category" field.
func TypeCategoryIn(vs ...string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldIn(FieldTypeCategory, vs...))
}

// TypeCategoryNotIn applies the NotIn predicate on the "type_category" field.
func TypeCategoryNotIn(vs ...string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNotIn(FieldTypeCategory, vs...))
}

// TypeCategoryGT applies the GT predicate on the "type_category" field.
func TypeCategoryGT(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGT(FieldTypeCategory, v))
}

// TypeCategoryGTE applies the GTE predicate on the "type_category" field.
func TypeCategoryGTE(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGTE(FieldTypeCategory, v))
}

// TypeCategoryLT applies the LT predicate on the "type_category" field.
func TypeCategoryLT(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLT(FieldTypeCategory, v))
}

// TypeCategoryLTE applies the LTE predicate on the "type_category" field.
func TypeCategoryLTE(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLTE(FieldTypeCategory, v))
}

// TypeCategoryContains applies the Contains predicate on the "type_category" field.
func TypeCategoryContains(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldContains(FieldTypeCategory, v))
}

// TypeCategoryHasPrefix applies the HasPrefix predicate on the "type_category" field.
func TypeCategoryHasPrefix(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldHasPrefix(FieldTypeCategory, v))
}

// TypeCategoryHasSuffix applies the HasSuffix predicate on the "type_category" field.
func TypeCategoryHasSuffix(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldHasSuffix(FieldTypeCategory, v))
}

// TypeCategoryEqualFold applies the EqualFold predicate on the "type_category" field.
func TypeCategoryEqualFold(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEqualFold(FieldTypeCategory, v))
}

// TypeCategoryContainsFold applies the ContainsFold predicate on the "type_category" field.
func TypeCategoryContainsFold(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldContainsFold(FieldTypeCategory, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldContainsFold(FieldName, v))
}

// PropertiesIsNil applies the IsNil predicate on the "properties" field.
func PropertiesIsNil() predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldIsNull(FieldProperties))
}

// PropertiesNotNil applies the NotNil predicate on the "properties" field.
func PropertiesNotNil() predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNotNull(FieldProperties))
}

// EmbeddingIsNil applies the IsNil predicate on the "embedding" field.
func EmbeddingIsNil() predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldIsNull(FieldEmbedding))
}

// EmbeddingNotNil applies the NotNil predicate on the "embedding" field.
func EmbeddingNotNil() predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNotNull(FieldEmbedding))
}

// ConfidenceScoreEQ applies the EQ predicate on the "confidence_score" field.
func ConfidenceScoreEQ(v float64) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldConfidenceScore, v))
}

// ConfidenceScoreNEQ applies the NEQ predicate on the "confidence_score" field.
func ConfidenceScoreNEQ(v float64) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNEQ(FieldConfidenceScore, v))
}

// ConfidenceScoreIn applies the In predicate on the "confidence_score" field.
func ConfidenceScoreIn(vs ...float64) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldIn(FieldConfidenceScore, vs...))
}

// ConfidenceScoreNotIn applies the NotIn predicate on the "confidence_score" field.
func ConfidenceScoreNotIn(vs ...float64) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNotIn(FieldConfidenceScore, vs...))
}

// ConfidenceScoreGT applies the GT predicate on the "confidence_score" field.
func ConfidenceScoreGT(v float64) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGT(FieldConfidenceScore, v))
}

// ConfidenceScoreGTE applies the GTE predicate on the "confidence_score" field.
func ConfidenceScoreGTE(v float64) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGTE(FieldConfidenceScore, v))
}

// ConfidenceScoreLT applies the LT predicate on the "confidence_score" field.
func ConfidenceScoreLT(v float64) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLT(FieldConfidenceScore, v))
}

// ConfidenceScoreLTE applies the LTE predicate on the "confidence_score" field.
func ConfidenceScoreLTE(v float64) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLTE(FieldConfidenceScore, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DiscoveredEntity) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DiscoveredEntity) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DiscoveredEntity) predicate.DiscoveredEntity {
	return predicate.DiscoveredEntity(sql.NotPredicates(p))
}
