// Code generated by ent, DO NOT EDIT.

package schemapromotion

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the schemapromotion type in the database.
	Label = "schema_promotion"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTypeName holds the string denoting the type_name field in the database.
	FieldTypeName = "type_name"
	// FieldPromotedAt holds the string denoting the promoted_at field in the database.
	FieldPromotedAt = "promoted_at"
	// FieldPromotionCriteria holds the string denoting the promotion_criteria field in the database.
	FieldPromotionCriteria = "promotion_criteria"
	// FieldEntitiesAffected holds the string denoting the entities_affected field in the database.
	FieldEntitiesAffected = "entities_affected"
	// FieldValidationFailures holds the string denoting the validation_failures field in the database.
	FieldValidationFailures = "validation_failures"
	// FieldSchemaDefinition holds the string denoting the schema_definition field in the database.
	FieldSchemaDefinition = "schema_definition"
	// Table holds the table name of the schemapromotion in the database.
	Table = "schema_promotions"
)

// Columns holds all SQL columns for schemapromotion fields.
var Columns = []string{
	FieldID,
	FieldTypeName,
	FieldPromotedAt,
	FieldPromotionCriteria,
	FieldEntitiesAffected,
	FieldValidationFailures,
	FieldSchemaDefinition,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TypeNameValidator is a validator for the "type_name" field. It is called by the builders before save.
	TypeNameValidator func(string) error
	// DefaultPromotedAt holds the default value on creation for the "promoted_at" field.
	DefaultPromotedAt func() time.Time
	// DefaultEntitiesAffected holds the default value on creation for the "entities_affected" field.
	DefaultEntitiesAffected int
	// EntitiesAffectedValidator is a validator for the "entities_affected" field. It is called by the builders before save.
	EntitiesAffectedValidator func(int) error
	// DefaultValidationFailures holds the default value on creation for the "validation_failures" field.
	DefaultValidationFailures int
	// ValidationFailuresValidator is a validator for the "validation_failures" field. It is called by the builders before save.
	ValidationFailuresValidator func(int) error
)

// OrderOption defines the ordering options for the SchemaPromotion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTypeName orders the results by the type_name field.
func ByTypeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTypeName, opts...).ToFunc()
}

// ByPromotedAt orders the results by the promoted_at field.
func ByPromotedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPromotedAt, opts...).ToFunc()
}

// ByEntitiesAffected orders the results by the entities_affected field.
func ByEntitiesAffected(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntitiesAffected, opts...).ToFunc()
}

// ByValidationFailures orders the results by the validation_failures field.
func ByValidationFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidationFailures, opts...).ToFunc()
}
