// Code generated by ent, DO NOT EDIT.

package schemapromotion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Blogem/enron-graph/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLTE(FieldID, id))
}

// TypeName applies equality check predicate on the "type_name" field. It's identical to TypeNameEQ.
func TypeName(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldTypeName, v))
}

// PromotedAt applies equality check predicate on the "promoted_at" field. It's identical to PromotedAtEQ.
func PromotedAt(v time.Time) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldPromotedAt, v))
}

// EntitiesAffected applies equality check predicate on the "entities_affected" field. It's identical to EntitiesAffectedEQ.
func EntitiesAffected(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldEntitiesAffected, v))
}

// ValidationFailures applies equality check predicate on the "validation_failures" field. It's identical to ValidationFailuresEQ.
func ValidationFailures(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldValidationFailures, v))
}

// TypeNameEQ applies the EQ predicate on the "type_name" field.
func TypeNameEQ(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldTypeName, v))
}

// TypeNameNEQ applies the NEQ predicate on the "type_name" field.
func TypeNameNEQ(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNEQ(FieldTypeName, v))
}

// TypeNameIn applies the In predicate on the "type_name" field.
func TypeNameIn(vs ...string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldIn(FieldTypeName, vs...))
}

// TypeNameNotIn applies the NotIn predicate on the "type_name" field.
func TypeNameNotIn(vs ...string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNotIn(FieldTypeName, vs...))
}

// TypeNameGT applies the GT predicate on the "type_name" field.
func TypeNameGT(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGT(FieldTypeName, v))
}

// TypeNameGTE applies the GTE predicate on the "type_name" field.
func TypeNameGTE(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGTE(FieldTypeName, v))
}

// TypeNameLT applies the LT predicate on the "type_name" field.
func TypeNameLT(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLT(FieldTypeName, v))
}

// TypeNameLTE applies the LTE predicate on the "type_name" field.
func TypeNameLTE(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLTE(FieldTypeName, v))
}

// TypeNameContains applies the Contains predicate on the "type_name" field.
func TypeNameContains(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldContains(FieldTypeName, v))
}

// TypeNameHasPrefix applies the HasPrefix predicate on the "type_name" field.
func TypeNameHasPrefix(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldHasPrefix(FieldTypeName, v))
}

// TypeNameHasSuffix applies the HasSuffix predicate on the "type_name" field.
func TypeNameHasSuffix(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldHasSuffix(FieldTypeName, v))
}

// TypeNameEqualFold applies the EqualFold predicate on the "type_name" field.
func TypeNameEqualFold(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEqualFold(FieldTypeName, v))
}

// TypeNameContainsFold applies the ContainsFold predicate on the "type_name" field.
func TypeNameContainsFold(v string) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldContainsFold(FieldTypeName, v))
}

// PromotedAtEQ applies the EQ predicate on the "promoted_at" field.
func PromotedAtEQ(v time.Time) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldPromotedAt, v))
}

// PromotedAtNEQ applies the NEQ predicate on the "promoted_at" field.
func PromotedAtNEQ(v time.Time) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNEQ(FieldPromotedAt, v))
}

// PromotedAtIn applies the In predicate on the "promoted_at" field.
func PromotedAtIn(vs ...time.Time) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldIn(FieldPromotedAt, vs...))
}

// PromotedAtNotIn applies the NotIn predicate on the "promoted_at" field.
func PromotedAtNotIn(vs ...time.Time) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNotIn(FieldPromotedAt, vs...))
}

// PromotedAtGT applies the GT predicate on the "promoted_at" field.
func PromotedAtGT(v time.Time) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGT(FieldPromotedAt, v))
}

// PromotedAtGTE applies the GTE predicate on the "promoted_at" field.
func PromotedAtGTE(v time.Time) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGTE(FieldPromotedAt, v))
}

// PromotedAtLT applies the LT predicate on the "promoted_at" field.
func PromotedAtLT(v time.Time) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLT(FieldPromotedAt, v))
}

// PromotedAtLTE applies the LTE predicate on the "promoted_at" field.
func PromotedAtLTE(v time.Time) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLTE(FieldPromotedAt, v))
}

// PromotionCriteriaIsNil applies the IsNil predicate on the "promotion_criteria" field.
func PromotionCriteriaIsNil() predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldIsNull(FieldPromotionCriteria))
}

// PromotionCriteriaNotNil applies the NotNil predicate on the "promotion_criteria" field.
func PromotionCriteriaNotNil() predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNotNull(FieldPromotionCriteria))
}

// EntitiesAffectedEQ applies the EQ predicate on the "entities_affected" field.
func EntitiesAffectedEQ(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldEntitiesAffected, v))
}

// EntitiesAffectedNEQ applies the NEQ predicate on the "entities_affected" field.
func EntitiesAffectedNEQ(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNEQ(FieldEntitiesAffected, v))
}

// EntitiesAffectedIn applies the In predicate on the "entities_affected" field.
func EntitiesAffectedIn(vs ...int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldIn(FieldEntitiesAffected, vs...))
}

// EntitiesAffectedNotIn applies the NotIn predicate on the "entities_affected" field.
func EntitiesAffectedNotIn(vs ...int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNotIn(FieldEntitiesAffected, vs...))
}

// EntitiesAffectedGT applies the GT predicate on the "entities_affected" field.
func EntitiesAffectedGT(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGT(FieldEntitiesAffected, v))
}

// EntitiesAffectedGTE applies the GTE predicate on the "entities_affected" field.
func EntitiesAffectedGTE(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGTE(FieldEntitiesAffected, v))
}

// EntitiesAffectedLT applies the LT predicate on the "entities_affected" field.
func EntitiesAffectedLT(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLT(FieldEntitiesAffected, v))
}

// EntitiesAffectedLTE applies the LTE predicate on the "entities_affected" field.
func EntitiesAffectedLTE(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLTE(FieldEntitiesAffected, v))
}

// ValidationFailuresEQ applies the EQ predicate on the "validation_failures" field.
func ValidationFailuresEQ(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldEQ(FieldValidationFailures, v))
}

// ValidationFailuresNEQ applies the NEQ predicate on the "validation_failures" field.
func ValidationFailuresNEQ(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNEQ(FieldValidationFailures, v))
}

// ValidationFailuresIn applies the In predicate on the "validation_failures" field.
func ValidationFailuresIn(vs ...int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldIn(FieldValidationFailures, vs...))
}

// ValidationFailuresNotIn applies the NotIn predicate on the "validation_failures" field.
func ValidationFailuresNotIn(vs ...int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNotIn(FieldValidationFailures, vs...))
}

// ValidationFailuresGT applies the GT predicate on the "validation_failures" field.
func ValidationFailuresGT(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGT(FieldValidationFailures, v))
}

// ValidationFailuresGTE applies the GTE predicate on the "validation_failures" field.
func ValidationFailuresGTE(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldGTE(FieldValidationFailures, v))
}

// ValidationFailuresLT applies the LT predicate on the "validation_failures" field.
func ValidationFailuresLT(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLT(FieldValidationFailures, v))
}

// ValidationFailuresLTE applies the LTE predicate on the "validation_failures" field.
func ValidationFailuresLTE(v int) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldLTE(FieldValidationFailures, v))
}

// SchemaDefinitionIsNil applies the IsNil predicate on the "schema_definition" field.
func SchemaDefinitionIsNil() predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldIsNull(FieldSchemaDefinition))
}

// SchemaDefinitionNotNil applies the NotNil predicate on the "schema_definition" field.
func SchemaDefinitionNotNil() predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.FieldNotNull(FieldSchemaDefinition))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SchemaPromotion) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SchemaPromotion) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SchemaPromotion) predicate.SchemaPromotion {
	return predicate.SchemaPromotion(sql.NotPredicates(p))
}
