package contract
package contract
































































































































































}	}		t.Fatalf("Failed to create test relationship 2: %v", err)	if err != nil {		Save(ctx)		SetExtractedAt(1234567891).		SetConfidence(0.80).		SetSourceID(fmt.Sprintf("%d", email2.ID)).		SetSourceType("email").		SetTargetEntityValue(email2.MessageID).		SetTargetEntityType("email").		SetSourceEntityValue(person1.EntityValue).		SetSourceEntityType("person").		SetRelationshipType("mentioned_in").	_, err = client.Relationship.Create().	}		t.Fatalf("Failed to create test relationship: %v", err)	if err != nil {		Save(ctx)		SetExtractedAt(1234567890).		SetConfidence(0.85).		SetSourceID(fmt.Sprintf("%d", email1.ID)).		SetSourceType("email").		SetTargetEntityValue(org1.EntityValue).		SetTargetEntityType("organization").		SetSourceEntityValue(person1.EntityValue).		SetSourceEntityType("person").		SetRelationshipType("works_for").	_, err = client.Relationship.Create().	// Create test relationships	}		t.Fatalf("Failed to create discovered entity org1: %v", err)	if err != nil {		Save(ctx)		SetExtractedAt(1234567890).		SetConfidence(0.90).		SetSourceID(fmt.Sprintf("%d", email1.ID)).		SetSourceType("email").		SetEntityValue("Enron Corp").		SetEntityType("organization").	org1, err := client.DiscoveredEntity.Create().	}		t.Fatalf("Failed to create discovered entity person1: %v", err)	if err != nil {		Save(ctx)		SetExtractedAt(1234567890).		SetConfidence(0.95).		SetSourceID(fmt.Sprintf("%d", email1.ID)).		SetSourceType("email").		SetEntityValue("John Doe").		SetEntityType("person").	person1, err := client.DiscoveredEntity.Create().	// Create test discovered entities	}		t.Fatalf("Failed to create test email 2: %v", err)	if err != nil {		Save(ctx)		SetBody("Test body 2").		SetTimestamp(1234567891).		SetReceiverAddr("receiver2@enron.com").		SetSenderAddr("sender2@enron.com").		SetSubject("Test Email 2").		SetMessageID("test2@enron.com").	email2, err := client.Email.Create().	}		t.Fatalf("Failed to create test email 1: %v", err)	if err != nil {		Save(ctx)		SetBody("Test body 1").		SetTimestamp(1234567890).		SetReceiverAddr("receiver1@enron.com").		SetSenderAddr("sender1@enron.com").		SetSubject("Test Email 1").		SetMessageID("test1@enron.com").	email1, err := client.Email.Create().	// Create test emails	}		t.Fatalf("Failed to create organization schema promotion: %v", err)	if err != nil {		Save(ctx)		SetPromotedAt(1234567890).		SetEntityType("organization").	_, err = client.SchemaPromotion.Create().	}		t.Fatalf("Failed to create person schema promotion: %v", err)	if err != nil {		Save(ctx)		SetPromotedAt(1234567890).		SetEntityType("person").	_, err := client.SchemaPromotion.Create().	// Create schema promotions for promoted types	ctx := context.Background()func SeedTestData(t *testing.T, client *ent.Client) {// SeedTestData creates a minimal set of test data for graph explorer tests}	}		t.Logf("Failed to clean schema promotions: %v", err)	if _, err := client.SchemaPromotion.Delete().Exec(ctx); err != nil {	}		t.Logf("Failed to clean discovered entities: %v", err)	if _, err := client.DiscoveredEntity.Delete().Exec(ctx); err != nil {	}		t.Logf("Failed to clean emails: %v", err)	if _, err := client.Email.Delete().Exec(ctx); err != nil {	}		t.Logf("Failed to clean relationships: %v", err)	if _, err := client.Relationship.Delete().Exec(ctx); err != nil {	// Delete all records in reverse dependency order		ctx := context.Background()func CleanupDB(t *testing.T, client *ent.Client) {// CleanupDB drops all data from the database (for PostgreSQL tests)}	return client	}		t.Fatalf("Failed to create schema: %v", err)		client.Close()	if err := client.Schema.Create(context.Background()); err != nil {	// Run migrations	}		t.Fatalf("Failed to connect to test database: %v", err)	if err != nil {	client, err := ent.Open("postgres", databaseURL)	databaseURL := "postgres://enron:enron@localhost:5432/enron_test?sslmode=disable"func TestClientPostgres(t *testing.T) *ent.Client {// Requires TEST_DATABASE_URL environment variable// TestClientPostgres creates a test ent client with a PostgreSQL test database}	return client	client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1", opts...)	}		enttest.WithOptions(ent.Log(t.Log)),	opts := []enttest.Option{func TestClient(t *testing.T) *ent.Client {// TestClient creates a test ent client with an in-memory SQLite database)	_ "github.com/mattn/go-sqlite3"	_ "github.com/lib/pq"	"github.com/Blogem/enron-graph/ent/enttest"	"github.com/Blogem/enron-graph/ent"	"testing"	"fmt"	"context"import (