// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DiscoveredEntitiesColumns holds the columns for the "discovered_entities" table.
	DiscoveredEntitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "unique_id", Type: field.TypeString, Unique: true},
		{Name: "type_category", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "properties", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "embedding", Type: field.TypeJSON, Nullable: true},
		{Name: "confidence_score", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// DiscoveredEntitiesTable holds the schema information for the "discovered_entities" table.
	DiscoveredEntitiesTable = &schema.Table{
		Name:       "discovered_entities",
		Columns:    DiscoveredEntitiesColumns,
		PrimaryKey: []*schema.Column{DiscoveredEntitiesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "discoveredentity_type_category",
				Unique:  false,
				Columns: []*schema.Column{DiscoveredEntitiesColumns[2]},
			},
			{
				Name:    "discoveredentity_name",
				Unique:  false,
				Columns: []*schema.Column{DiscoveredEntitiesColumns[3]},
			},
			{
				Name:    "discoveredentity_confidence_score",
				Unique:  false,
				Columns: []*schema.Column{DiscoveredEntitiesColumns[6]},
			},
		},
	}
	// EmailsColumns holds the columns for the "emails" table.
	EmailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "message_id", Type: field.TypeString, Unique: true},
		{Name: "from", Type: field.TypeString},
		{Name: "to", Type: field.TypeJSON, Nullable: true},
		{Name: "cc", Type: field.TypeJSON, Nullable: true},
		{Name: "bcc", Type: field.TypeJSON, Nullable: true},
		{Name: "subject", Type: field.TypeString, Default: ""},
		{Name: "date", Type: field.TypeTime},
		{Name: "body", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "file_path", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// EmailsTable holds the schema information for the "emails" table.
	EmailsTable = &schema.Table{
		Name:       "emails",
		Columns:    EmailsColumns,
		PrimaryKey: []*schema.Column{EmailsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "email_date",
				Unique:  false,
				Columns: []*schema.Column{EmailsColumns[7]},
			},
			{
				Name:    "email_from",
				Unique:  false,
				Columns: []*schema.Column{EmailsColumns[2]},
			},
		},
	}
	// RelationshipsColumns holds the columns for the "relationships" table.
	RelationshipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "from_type", Type: field.TypeString},
		{Name: "from_id", Type: field.TypeInt},
		{Name: "to_type", Type: field.TypeString},
		{Name: "to_id", Type: field.TypeInt},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "confidence_score", Type: field.TypeFloat64, Default: 1},
		{Name: "properties", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "created_at", Type: field.TypeTime},
	}
	// RelationshipsTable holds the schema information for the "relationships" table.
	RelationshipsTable = &schema.Table{
		Name:       "relationships",
		Columns:    RelationshipsColumns,
		PrimaryKey: []*schema.Column{RelationshipsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "relationship_type",
				Unique:  false,
				Columns: []*schema.Column{RelationshipsColumns[1]},
			},
			{
				Name:    "relationship_from_type_from_id",
				Unique:  false,
				Columns: []*schema.Column{RelationshipsColumns[2], RelationshipsColumns[3]},
			},
			{
				Name:    "relationship_to_type_to_id",
				Unique:  false,
				Columns: []*schema.Column{RelationshipsColumns[4], RelationshipsColumns[5]},
			},
			{
				Name:    "relationship_timestamp",
				Unique:  false,
				Columns: []*schema.Column{RelationshipsColumns[6]},
			},
		},
	}
	// SchemaPromotionsColumns holds the columns for the "schema_promotions" table.
	SchemaPromotionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type_name", Type: field.TypeString},
		{Name: "promoted_at", Type: field.TypeTime},
		{Name: "promotion_criteria", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
		{Name: "entities_affected", Type: field.TypeInt, Default: 0},
		{Name: "validation_failures", Type: field.TypeInt, Default: 0},
		{Name: "schema_definition", Type: field.TypeJSON, Nullable: true, SchemaType: map[string]string{"postgres": "jsonb"}},
	}
	// SchemaPromotionsTable holds the schema information for the "schema_promotions" table.
	SchemaPromotionsTable = &schema.Table{
		Name:       "schema_promotions",
		Columns:    SchemaPromotionsColumns,
		PrimaryKey: []*schema.Column{SchemaPromotionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "schemapromotion_type_name",
				Unique:  false,
				Columns: []*schema.Column{SchemaPromotionsColumns[1]},
			},
			{
				Name:    "schemapromotion_promoted_at",
				Unique:  false,
				Columns: []*schema.Column{SchemaPromotionsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DiscoveredEntitiesTable,
		EmailsTable,
		RelationshipsTable,
		SchemaPromotionsTable,
	}
)

func init() {
}
