// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Blogem/enron-graph/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/Blogem/enron-graph/ent/discoveredentity"
	"github.com/Blogem/enron-graph/ent/email"
	"github.com/Blogem/enron-graph/ent/relationship"
	"github.com/Blogem/enron-graph/ent/schemapromotion"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DiscoveredEntity is the client for interacting with the DiscoveredEntity builders.
	DiscoveredEntity *DiscoveredEntityClient
	// Email is the client for interacting with the Email builders.
	Email *EmailClient
	// Relationship is the client for interacting with the Relationship builders.
	Relationship *RelationshipClient
	// SchemaPromotion is the client for interacting with the SchemaPromotion builders.
	SchemaPromotion *SchemaPromotionClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.DiscoveredEntity = NewDiscoveredEntityClient(c.config)
	c.Email = NewEmailClient(c.config)
	c.Relationship = NewRelationshipClient(c.config)
	c.SchemaPromotion = NewSchemaPromotionClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		DiscoveredEntity: NewDiscoveredEntityClient(cfg),
		Email:            NewEmailClient(cfg),
		Relationship:     NewRelationshipClient(cfg),
		SchemaPromotion:  NewSchemaPromotionClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		DiscoveredEntity: NewDiscoveredEntityClient(cfg),
		Email:            NewEmailClient(cfg),
		Relationship:     NewRelationshipClient(cfg),
		SchemaPromotion:  NewSchemaPromotionClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DiscoveredEntity.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.DiscoveredEntity.Use(hooks...)
	c.Email.Use(hooks...)
	c.Relationship.Use(hooks...)
	c.SchemaPromotion.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.DiscoveredEntity.Intercept(interceptors...)
	c.Email.Intercept(interceptors...)
	c.Relationship.Intercept(interceptors...)
	c.SchemaPromotion.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *DiscoveredEntityMutation:
		return c.DiscoveredEntity.mutate(ctx, m)
	case *EmailMutation:
		return c.Email.mutate(ctx, m)
	case *RelationshipMutation:
		return c.Relationship.mutate(ctx, m)
	case *SchemaPromotionMutation:
		return c.SchemaPromotion.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// DiscoveredEntityClient is a client for the DiscoveredEntity schema.
type DiscoveredEntityClient struct {
	config
}

// NewDiscoveredEntityClient returns a client for the DiscoveredEntity from the given config.
func NewDiscoveredEntityClient(c config) *DiscoveredEntityClient {
	return &DiscoveredEntityClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `discoveredentity.Hooks(f(g(h())))`.
func (c *DiscoveredEntityClient) Use(hooks ...Hook) {
	c.hooks.DiscoveredEntity = append(c.hooks.DiscoveredEntity, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `discoveredentity.Intercept(f(g(h())))`.
func (c *DiscoveredEntityClient) Intercept(interceptors ...Interceptor) {
	c.inters.DiscoveredEntity = append(c.inters.DiscoveredEntity, interceptors...)
}

// Create returns a builder for creating a DiscoveredEntity entity.
func (c *DiscoveredEntityClient) Create() *DiscoveredEntityCreate {
	mutation := newDiscoveredEntityMutation(c.config, OpCreate)
	return &DiscoveredEntityCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DiscoveredEntity entities.
func (c *DiscoveredEntityClient) CreateBulk(builders ...*DiscoveredEntityCreate) *DiscoveredEntityCreateBulk {
	return &DiscoveredEntityCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DiscoveredEntityClient) MapCreateBulk(slice any, setFunc func(*DiscoveredEntityCreate, int)) *DiscoveredEntityCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DiscoveredEntityCreateBulk{err: fmt.Errorf("calling to DiscoveredEntityClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DiscoveredEntityCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DiscoveredEntityCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DiscoveredEntity.
func (c *DiscoveredEntityClient) Update() *DiscoveredEntityUpdate {
	mutation := newDiscoveredEntityMutation(c.config, OpUpdate)
	return &DiscoveredEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DiscoveredEntityClient) UpdateOne(_m *DiscoveredEntity) *DiscoveredEntityUpdateOne {
	mutation := newDiscoveredEntityMutation(c.config, OpUpdateOne, withDiscoveredEntity(_m))
	return &DiscoveredEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DiscoveredEntityClient) UpdateOneID(id int) *DiscoveredEntityUpdateOne {
	mutation := newDiscoveredEntityMutation(c.config, OpUpdateOne, withDiscoveredEntityID(id))
	return &DiscoveredEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DiscoveredEntity.
func (c *DiscoveredEntityClient) Delete() *DiscoveredEntityDelete {
	mutation := newDiscoveredEntityMutation(c.config, OpDelete)
	return &DiscoveredEntityDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DiscoveredEntityClient) DeleteOne(_m *DiscoveredEntity) *DiscoveredEntityDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DiscoveredEntityClient) DeleteOneID(id int) *DiscoveredEntityDeleteOne {
	builder := c.Delete().Where(discoveredentity.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DiscoveredEntityDeleteOne{builder}
}

// Query returns a query builder for DiscoveredEntity.
func (c *DiscoveredEntityClient) Query() *DiscoveredEntityQuery {
	return &DiscoveredEntityQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDiscoveredEntity},
		inters: c.Interceptors(),
	}
}

// Get returns a DiscoveredEntity entity by its id.
func (c *DiscoveredEntityClient) Get(ctx context.Context, id int) (*DiscoveredEntity, error) {
	return c.Query().Where(discoveredentity.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DiscoveredEntityClient) GetX(ctx context.Context, id int) *DiscoveredEntity {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DiscoveredEntityClient) Hooks() []Hook {
	return c.hooks.DiscoveredEntity
}

// Interceptors returns the client interceptors.
func (c *DiscoveredEntityClient) Interceptors() []Interceptor {
	return c.inters.DiscoveredEntity
}

func (c *DiscoveredEntityClient) mutate(ctx context.Context, m *DiscoveredEntityMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DiscoveredEntityCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DiscoveredEntityUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DiscoveredEntityUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DiscoveredEntityDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DiscoveredEntity mutation op: %q", m.Op())
	}
}

// EmailClient is a client for the Email schema.
type EmailClient struct {
	config
}

// NewEmailClient returns a client for the Email from the given config.
func NewEmailClient(c config) *EmailClient {
	return &EmailClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `email.Hooks(f(g(h())))`.
func (c *EmailClient) Use(hooks ...Hook) {
	c.hooks.Email = append(c.hooks.Email, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `email.Intercept(f(g(h())))`.
func (c *EmailClient) Intercept(interceptors ...Interceptor) {
	c.inters.Email = append(c.inters.Email, interceptors...)
}

// Create returns a builder for creating a Email entity.
func (c *EmailClient) Create() *EmailCreate {
	mutation := newEmailMutation(c.config, OpCreate)
	return &EmailCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Email entities.
func (c *EmailClient) CreateBulk(builders ...*EmailCreate) *EmailCreateBulk {
	return &EmailCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EmailClient) MapCreateBulk(slice any, setFunc func(*EmailCreate, int)) *EmailCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EmailCreateBulk{err: fmt.Errorf("calling to EmailClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EmailCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EmailCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Email.
func (c *EmailClient) Update() *EmailUpdate {
	mutation := newEmailMutation(c.config, OpUpdate)
	return &EmailUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EmailClient) UpdateOne(_m *Email) *EmailUpdateOne {
	mutation := newEmailMutation(c.config, OpUpdateOne, withEmail(_m))
	return &EmailUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EmailClient) UpdateOneID(id int) *EmailUpdateOne {
	mutation := newEmailMutation(c.config, OpUpdateOne, withEmailID(id))
	return &EmailUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Email.
func (c *EmailClient) Delete() *EmailDelete {
	mutation := newEmailMutation(c.config, OpDelete)
	return &EmailDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EmailClient) DeleteOne(_m *Email) *EmailDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EmailClient) DeleteOneID(id int) *EmailDeleteOne {
	builder := c.Delete().Where(email.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EmailDeleteOne{builder}
}

// Query returns a query builder for Email.
func (c *EmailClient) Query() *EmailQuery {
	return &EmailQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEmail},
		inters: c.Interceptors(),
	}
}

// Get returns a Email entity by its id.
func (c *EmailClient) Get(ctx context.Context, id int) (*Email, error) {
	return c.Query().Where(email.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EmailClient) GetX(ctx context.Context, id int) *Email {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *EmailClient) Hooks() []Hook {
	return c.hooks.Email
}

// Interceptors returns the client interceptors.
func (c *EmailClient) Interceptors() []Interceptor {
	return c.inters.Email
}

func (c *EmailClient) mutate(ctx context.Context, m *EmailMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EmailCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EmailUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EmailUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EmailDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Email mutation op: %q", m.Op())
	}
}

// RelationshipClient is a client for the Relationship schema.
type RelationshipClient struct {
	config
}

// NewRelationshipClient returns a client for the Relationship from the given config.
func NewRelationshipClient(c config) *RelationshipClient {
	return &RelationshipClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `relationship.Hooks(f(g(h())))`.
func (c *RelationshipClient) Use(hooks ...Hook) {
	c.hooks.Relationship = append(c.hooks.Relationship, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `relationship.Intercept(f(g(h())))`.
func (c *RelationshipClient) Intercept(interceptors ...Interceptor) {
	c.inters.Relationship = append(c.inters.Relationship, interceptors...)
}

// Create returns a builder for creating a Relationship entity.
func (c *RelationshipClient) Create() *RelationshipCreate {
	mutation := newRelationshipMutation(c.config, OpCreate)
	return &RelationshipCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Relationship entities.
func (c *RelationshipClient) CreateBulk(builders ...*RelationshipCreate) *RelationshipCreateBulk {
	return &RelationshipCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RelationshipClient) MapCreateBulk(slice any, setFunc func(*RelationshipCreate, int)) *RelationshipCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RelationshipCreateBulk{err: fmt.Errorf("calling to RelationshipClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RelationshipCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RelationshipCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Relationship.
func (c *RelationshipClient) Update() *RelationshipUpdate {
	mutation := newRelationshipMutation(c.config, OpUpdate)
	return &RelationshipUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RelationshipClient) UpdateOne(_m *Relationship) *RelationshipUpdateOne {
	mutation := newRelationshipMutation(c.config, OpUpdateOne, withRelationship(_m))
	return &RelationshipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RelationshipClient) UpdateOneID(id int) *RelationshipUpdateOne {
	mutation := newRelationshipMutation(c.config, OpUpdateOne, withRelationshipID(id))
	return &RelationshipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Relationship.
func (c *RelationshipClient) Delete() *RelationshipDelete {
	mutation := newRelationshipMutation(c.config, OpDelete)
	return &RelationshipDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RelationshipClient) DeleteOne(_m *Relationship) *RelationshipDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RelationshipClient) DeleteOneID(id int) *RelationshipDeleteOne {
	builder := c.Delete().Where(relationship.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RelationshipDeleteOne{builder}
}

// Query returns a query builder for Relationship.
func (c *RelationshipClient) Query() *RelationshipQuery {
	return &RelationshipQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRelationship},
		inters: c.Interceptors(),
	}
}

// Get returns a Relationship entity by its id.
func (c *RelationshipClient) Get(ctx context.Context, id int) (*Relationship, error) {
	return c.Query().Where(relationship.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RelationshipClient) GetX(ctx context.Context, id int) *Relationship {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RelationshipClient) Hooks() []Hook {
	return c.hooks.Relationship
}

// Interceptors returns the client interceptors.
func (c *RelationshipClient) Interceptors() []Interceptor {
	return c.inters.Relationship
}

func (c *RelationshipClient) mutate(ctx context.Context, m *RelationshipMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RelationshipCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RelationshipUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RelationshipUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RelationshipDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Relationship mutation op: %q", m.Op())
	}
}

// SchemaPromotionClient is a client for the SchemaPromotion schema.
type SchemaPromotionClient struct {
	config
}

// NewSchemaPromotionClient returns a client for the SchemaPromotion from the given config.
func NewSchemaPromotionClient(c config) *SchemaPromotionClient {
	return &SchemaPromotionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `schemapromotion.Hooks(f(g(h())))`.
func (c *SchemaPromotionClient) Use(hooks ...Hook) {
	c.hooks.SchemaPromotion = append(c.hooks.SchemaPromotion, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `schemapromotion.Intercept(f(g(h())))`.
func (c *SchemaPromotionClient) Intercept(interceptors ...Interceptor) {
	c.inters.SchemaPromotion = append(c.inters.SchemaPromotion, interceptors...)
}

// Create returns a builder for creating a SchemaPromotion entity.
func (c *SchemaPromotionClient) Create() *SchemaPromotionCreate {
	mutation := newSchemaPromotionMutation(c.config, OpCreate)
	return &SchemaPromotionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SchemaPromotion entities.
func (c *SchemaPromotionClient) CreateBulk(builders ...*SchemaPromotionCreate) *SchemaPromotionCreateBulk {
	return &SchemaPromotionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SchemaPromotionClient) MapCreateBulk(slice any, setFunc func(*SchemaPromotionCreate, int)) *SchemaPromotionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SchemaPromotionCreateBulk{err: fmt.Errorf("calling to SchemaPromotionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SchemaPromotionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SchemaPromotionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SchemaPromotion.
func (c *SchemaPromotionClient) Update() *SchemaPromotionUpdate {
	mutation := newSchemaPromotionMutation(c.config, OpUpdate)
	return &SchemaPromotionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SchemaPromotionClient) UpdateOne(_m *SchemaPromotion) *SchemaPromotionUpdateOne {
	mutation := newSchemaPromotionMutation(c.config, OpUpdateOne, withSchemaPromotion(_m))
	return &SchemaPromotionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SchemaPromotionClient) UpdateOneID(id int) *SchemaPromotionUpdateOne {
	mutation := newSchemaPromotionMutation(c.config, OpUpdateOne, withSchemaPromotionID(id))
	return &SchemaPromotionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SchemaPromotion.
func (c *SchemaPromotionClient) Delete() *SchemaPromotionDelete {
	mutation := newSchemaPromotionMutation(c.config, OpDelete)
	return &SchemaPromotionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SchemaPromotionClient) DeleteOne(_m *SchemaPromotion) *SchemaPromotionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SchemaPromotionClient) DeleteOneID(id int) *SchemaPromotionDeleteOne {
	builder := c.Delete().Where(schemapromotion.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SchemaPromotionDeleteOne{builder}
}

// Query returns a query builder for SchemaPromotion.
func (c *SchemaPromotionClient) Query() *SchemaPromotionQuery {
	return &SchemaPromotionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSchemaPromotion},
		inters: c.Interceptors(),
	}
}

// Get returns a SchemaPromotion entity by its id.
func (c *SchemaPromotionClient) Get(ctx context.Context, id int) (*SchemaPromotion, error) {
	return c.Query().Where(schemapromotion.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SchemaPromotionClient) GetX(ctx context.Context, id int) *SchemaPromotion {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SchemaPromotionClient) Hooks() []Hook {
	return c.hooks.SchemaPromotion
}

// Interceptors returns the client interceptors.
func (c *SchemaPromotionClient) Interceptors() []Interceptor {
	return c.inters.SchemaPromotion
}

func (c *SchemaPromotionClient) mutate(ctx context.Context, m *SchemaPromotionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SchemaPromotionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SchemaPromotionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SchemaPromotionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SchemaPromotionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SchemaPromotion mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		DiscoveredEntity, Email, Relationship, SchemaPromotion []ent.Hook
	}
	inters struct {
		DiscoveredEntity, Email, Relationship, SchemaPromotion []ent.Interceptor
	}
)
