// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Blogem/enron-graph/ent/discoveredentity"
	"github.com/Blogem/enron-graph/ent/predicate"
)

// DiscoveredEntityUpdate is the builder for updating DiscoveredEntity entities.
type DiscoveredEntityUpdate struct {
	config
	hooks    []Hook
	mutation *DiscoveredEntityMutation
}

// Where appends a list predicates to the DiscoveredEntityUpdate builder.
func (_u *DiscoveredEntityUpdate) Where(ps ...predicate.DiscoveredEntity) *DiscoveredEntityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUniqueID sets the "unique_id" field.
func (_u *DiscoveredEntityUpdate) SetUniqueID(v string) *DiscoveredEntityUpdate {
	_u.mutation.SetUniqueID(v)
	return _u
}

// SetNillableUniqueID sets the "unique_id" field if the given value is not nil.
func (_u *DiscoveredEntityUpdate) SetNillableUniqueID(v *string) *DiscoveredEntityUpdate {
	if v != nil {
		_u.SetUniqueID(*v)
	}
	return _u
}

// SetTypeCategory sets the "type_category" field.
func (_u *DiscoveredEntityUpdate) SetTypeCategory(v string) *DiscoveredEntityUpdate {
	_u.mutation.SetTypeCategory(v)
	return _u
}

// SetNillableTypeCategory sets the "type_category" field if the given value is not nil.
func (_u *DiscoveredEntityUpdate) SetNillableTypeCategory(v *string) *DiscoveredEntityUpdate {
	if v != nil {
		_u.SetTypeCategory(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DiscoveredEntityUpdate) SetName(v string) *DiscoveredEntityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DiscoveredEntityUpdate) SetNillableName(v *string) *DiscoveredEntityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProperties sets the "properties" field.
func (_u *DiscoveredEntityUpdate) SetProperties(v map[string]interface{}) *DiscoveredEntityUpdate {
	_u.mutation.SetProperties(v)
	return _u
}

// ClearProperties clears the value of the "properties" field.
func (_u *DiscoveredEntityUpdate) ClearProperties() *DiscoveredEntityUpdate {
	_u.mutation.ClearProperties()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *DiscoveredEntityUpdate) SetEmbedding(v []float32) *DiscoveredEntityUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *DiscoveredEntityUpdate) AppendEmbedding(v []float32) *DiscoveredEntityUpdate {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *DiscoveredEntityUpdate) ClearEmbedding() *DiscoveredEntityUpdate {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetConfidenceScore sets the "confidence_score" field.
func (_u *DiscoveredEntityUpdate) SetConfidenceScore(v float64) *DiscoveredEntityUpdate {
	_u.mutation.ResetConfidenceScore()
	_u.mutation.SetConfidenceScore(v)
	return _u
}

// SetNillableConfidenceScore sets the "confidence_score" field if the given value is not nil.
func (_u *DiscoveredEntityUpdate) SetNillableConfidenceScore(v *float64) *DiscoveredEntityUpdate {
	if v != nil {
		_u.SetConfidenceScore(*v)
	}
	return _u
}

// AddConfidenceScore adds value to the "confidence_score" field.
func (_u *DiscoveredEntityUpdate) AddConfidenceScore(v float64) *DiscoveredEntityUpdate {
	_u.mutation.AddConfidenceScore(v)
	return _u
}

// Mutation returns the DiscoveredEntityMutation object of the builder.
func (_u *DiscoveredEntityUpdate) Mutation() *DiscoveredEntityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DiscoveredEntityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscoveredEntityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DiscoveredEntityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscoveredEntityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscoveredEntityUpdate) check() error {
	if v, ok := _u.mutation.UniqueID(); ok {
		if err := discoveredentity.UniqueIDValidator(v); err != nil {
			return &ValidationError{Name: "unique_id", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.unique_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TypeCategory(); ok {
		if err := discoveredentity.TypeCategoryValidator(v); err != nil {
			return &ValidationError{Name: "type_category", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.type_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := discoveredentity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfidenceScore(); ok {
		if err := discoveredentity.ConfidenceScoreValidator(v); err != nil {
			return &ValidationError{Name: "confidence_score", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.confidence_score": %w`, err)}
		}
	}
	return nil
}

func (_u *DiscoveredEntityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discoveredentity.Table, discoveredentity.Columns, sqlgraph.NewFieldSpec(discoveredentity.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UniqueID(); ok {
		_spec.SetField(discoveredentity.FieldUniqueID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TypeCategory(); ok {
		_spec.SetField(discoveredentity.FieldTypeCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(discoveredentity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Properties(); ok {
		_spec.SetField(discoveredentity.FieldProperties, field.TypeJSON, value)
	}
	if _u.mutation.PropertiesCleared() {
		_spec.ClearField(discoveredentity.FieldProperties, field.TypeJSON)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(discoveredentity.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, discoveredentity.FieldEmbedding, value)
		})
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(discoveredentity.FieldEmbedding, field.TypeJSON)
	}
	if value, ok := _u.mutation.ConfidenceScore(); ok {
		_spec.SetField(discoveredentity.FieldConfidenceScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidenceScore(); ok {
		_spec.AddField(discoveredentity.FieldConfidenceScore, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discoveredentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DiscoveredEntityUpdateOne is the builder for updating a single DiscoveredEntity entity.
type DiscoveredEntityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DiscoveredEntityMutation
}

// SetUniqueID sets the "unique_id" field.
func (_u *DiscoveredEntityUpdateOne) SetUniqueID(v string) *DiscoveredEntityUpdateOne {
	_u.mutation.SetUniqueID(v)
	return _u
}

// SetNillableUniqueID sets the "unique_id" field if the given value is not nil.
func (_u *DiscoveredEntityUpdateOne) SetNillableUniqueID(v *string) *DiscoveredEntityUpdateOne {
	if v != nil {
		_u.SetUniqueID(*v)
	}
	return _u
}

// SetTypeCategory sets the "type_category" field.
func (_u *DiscoveredEntityUpdateOne) SetTypeCategory(v string) *DiscoveredEntityUpdateOne {
	_u.mutation.SetTypeCategory(v)
	return _u
}

// SetNillableTypeCategory sets the "type_category" field if the given value is not nil.
func (_u *DiscoveredEntityUpdateOne) SetNillableTypeCategory(v *string) *DiscoveredEntityUpdateOne {
	if v != nil {
		_u.SetTypeCategory(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DiscoveredEntityUpdateOne) SetName(v string) *DiscoveredEntityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DiscoveredEntityUpdateOne) SetNillableName(v *string) *DiscoveredEntityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProperties sets the "properties" field.
func (_u *DiscoveredEntityUpdateOne) SetProperties(v map[string]interface{}) *DiscoveredEntityUpdateOne {
	_u.mutation.SetProperties(v)
	return _u
}

// ClearProperties clears the value of the "properties" field.
func (_u *DiscoveredEntityUpdateOne) ClearProperties() *DiscoveredEntityUpdateOne {
	_u.mutation.ClearProperties()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *DiscoveredEntityUpdateOne) SetEmbedding(v []float32) *DiscoveredEntityUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *DiscoveredEntityUpdateOne) AppendEmbedding(v []float32) *DiscoveredEntityUpdateOne {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *DiscoveredEntityUpdateOne) ClearEmbedding() *DiscoveredEntityUpdateOne {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetConfidenceScore sets the "confidence_score" field.
func (_u *DiscoveredEntityUpdateOne) SetConfidenceScore(v float64) *DiscoveredEntityUpdateOne {
	_u.mutation.ResetConfidenceScore()
	_u.mutation.SetConfidenceScore(v)
	return _u
}

// SetNillableConfidenceScore sets the "confidence_score" field if the given value is not nil.
func (_u *DiscoveredEntityUpdateOne) SetNillableConfidenceScore(v *float64) *DiscoveredEntityUpdateOne {
	if v != nil {
		_u.SetConfidenceScore(*v)
	}
	return _u
}

// AddConfidenceScore adds value to the "confidence_score" field.
func (_u *DiscoveredEntityUpdateOne) AddConfidenceScore(v float64) *DiscoveredEntityUpdateOne {
	_u.mutation.AddConfidenceScore(v)
	return _u
}

// Mutation returns the DiscoveredEntityMutation object of the builder.
func (_u *DiscoveredEntityUpdateOne) Mutation() *DiscoveredEntityMutation {
	return _u.mutation
}

// Where appends a list predicates to the DiscoveredEntityUpdate builder.
func (_u *DiscoveredEntityUpdateOne) Where(ps ...predicate.DiscoveredEntity) *DiscoveredEntityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DiscoveredEntityUpdateOne) Select(field string, fields ...string) *DiscoveredEntityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DiscoveredEntity entity.
func (_u *DiscoveredEntityUpdateOne) Save(ctx context.Context) (*DiscoveredEntity, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DiscoveredEntityUpdateOne) SaveX(ctx context.Context) *DiscoveredEntity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DiscoveredEntityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DiscoveredEntityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DiscoveredEntityUpdateOne) check() error {
	if v, ok := _u.mutation.UniqueID(); ok {
		if err := discoveredentity.UniqueIDValidator(v); err != nil {
			return &ValidationError{Name: "unique_id", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.unique_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TypeCategory(); ok {
		if err := discoveredentity.TypeCategoryValidator(v); err != nil {
			return &ValidationError{Name: "type_category", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.type_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := discoveredentity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfidenceScore(); ok {
		if err := discoveredentity.ConfidenceScoreValidator(v); err != nil {
			return &ValidationError{Name: "confidence_score", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.confidence_score": %w`, err)}
		}
	}
	return nil
}

func (_u *DiscoveredEntityUpdateOne) sqlSave(ctx context.Context) (_node *DiscoveredEntity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(discoveredentity.Table, discoveredentity.Columns, sqlgraph.NewFieldSpec(discoveredentity.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DiscoveredEntity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discoveredentity.FieldID)
		for _, f := range fields {
			if !discoveredentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != discoveredentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UniqueID(); ok {
		_spec.SetField(discoveredentity.FieldUniqueID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TypeCategory(); ok {
		_spec.SetField(discoveredentity.FieldTypeCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(discoveredentity.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Properties(); ok {
		_spec.SetField(discoveredentity.FieldProperties, field.TypeJSON, value)
	}
	if _u.mutation.PropertiesCleared() {
		_spec.ClearField(discoveredentity.FieldProperties, field.TypeJSON)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(discoveredentity.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, discoveredentity.FieldEmbedding, value)
		})
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(discoveredentity.FieldEmbedding, field.TypeJSON)
	}
	if value, ok := _u.mutation.ConfidenceScore(); ok {
		_spec.SetField(discoveredentity.FieldConfidenceScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidenceScore(); ok {
		_spec.AddField(discoveredentity.FieldConfidenceScore, field.TypeFloat64, value)
	}
	_node = &DiscoveredEntity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{discoveredentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
