// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blogem/enron-graph/ent/discoveredentity"
	"github.com/Blogem/enron-graph/ent/predicate"
)

// DiscoveredEntityDelete is the builder for deleting a DiscoveredEntity entity.
type DiscoveredEntityDelete struct {
	config
	hooks    []Hook
	mutation *DiscoveredEntityMutation
}

// Where appends a list predicates to the DiscoveredEntityDelete builder.
func (_d *DiscoveredEntityDelete) Where(ps ...predicate.DiscoveredEntity) *DiscoveredEntityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DiscoveredEntityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscoveredEntityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DiscoveredEntityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(discoveredentity.Table, sqlgraph.NewFieldSpec(discoveredentity.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DiscoveredEntityDeleteOne is the builder for deleting a single DiscoveredEntity entity.
type DiscoveredEntityDeleteOne struct {
	_d *DiscoveredEntityDelete
}

// Where appends a list predicates to the DiscoveredEntityDelete builder.
func (_d *DiscoveredEntityDeleteOne) Where(ps ...predicate.DiscoveredEntity) *DiscoveredEntityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DiscoveredEntityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{discoveredentity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DiscoveredEntityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
