// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blogem/enron-graph/ent/discoveredentity"
)

// DiscoveredEntityCreate is the builder for creating a DiscoveredEntity entity.
type DiscoveredEntityCreate struct {
	config
	mutation *DiscoveredEntityMutation
	hooks    []Hook
}

// SetUniqueID sets the "unique_id" field.
func (_c *DiscoveredEntityCreate) SetUniqueID(v string) *DiscoveredEntityCreate {
	_c.mutation.SetUniqueID(v)
	return _c
}

// SetTypeCategory sets the "type_category" field.
func (_c *DiscoveredEntityCreate) SetTypeCategory(v string) *DiscoveredEntityCreate {
	_c.mutation.SetTypeCategory(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DiscoveredEntityCreate) SetName(v string) *DiscoveredEntityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProperties sets the "properties" field.
func (_c *DiscoveredEntityCreate) SetProperties(v map[string]interface{}) *DiscoveredEntityCreate {
	_c.mutation.SetProperties(v)
	return _c
}

// SetEmbedding sets the "embedding" field.
func (_c *DiscoveredEntityCreate) SetEmbedding(v []float32) *DiscoveredEntityCreate {
	_c.mutation.SetEmbedding(v)
	return _c
}

// SetConfidenceScore sets the "confidence_score" field.
func (_c *DiscoveredEntityCreate) SetConfidenceScore(v float64) *DiscoveredEntityCreate {
	_c.mutation.SetConfidenceScore(v)
	return _c
}

// SetNillableConfidenceScore sets the "confidence_score" field if the given value is not nil.
func (_c *DiscoveredEntityCreate) SetNillableConfidenceScore(v *float64) *DiscoveredEntityCreate {
	if v != nil {
		_c.SetConfidenceScore(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DiscoveredEntityCreate) SetCreatedAt(v time.Time) *DiscoveredEntityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DiscoveredEntityCreate) SetNillableCreatedAt(v *time.Time) *DiscoveredEntityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the DiscoveredEntityMutation object of the builder.
func (_c *DiscoveredEntityCreate) Mutation() *DiscoveredEntityMutation {
	return _c.mutation
}

// Save creates the DiscoveredEntity in the database.
func (_c *DiscoveredEntityCreate) Save(ctx context.Context) (*DiscoveredEntity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DiscoveredEntityCreate) SaveX(ctx context.Context) *DiscoveredEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscoveredEntityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscoveredEntityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DiscoveredEntityCreate) defaults() {
	if _, ok := _c.mutation.ConfidenceScore(); !ok {
		v := discoveredentity.DefaultConfidenceScore
		_c.mutation.SetConfidenceScore(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := discoveredentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DiscoveredEntityCreate) check() error {
	if _, ok := _c.mutation.UniqueID(); !ok {
		return &ValidationError{Name: "unique_id", err: errors.New(`ent: missing required field "DiscoveredEntity.unique_id"`)}
	}
	if v, ok := _c.mutation.UniqueID(); ok {
		if err := discoveredentity.UniqueIDValidator(v); err != nil {
			return &ValidationError{Name: "unique_id", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.unique_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TypeCategory(); !ok {
		return &ValidationError{Name: "type_category", err: errors.New(`ent: missing required field "DiscoveredEntity.type_category"`)}
	}
	if v, ok := _c.mutation.TypeCategory(); ok {
		if err := discoveredentity.TypeCategoryValidator(v); err != nil {
			return &ValidationError{Name: "type_category", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.type_category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DiscoveredEntity.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := discoveredentity.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ConfidenceScore(); !ok {
		return &ValidationError{Name: "confidence_score", err: errors.New(`ent: missing required field "DiscoveredEntity.confidence_score"`)}
	}
	if v, ok := _c.mutation.ConfidenceScore(); ok {
		if err := discoveredentity.ConfidenceScoreValidator(v); err != nil {
			return &ValidationError{Name: "confidence_score", err: fmt.Errorf(`ent: validator failed for field "DiscoveredEntity.confidence_score": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DiscoveredEntity.created_at"`)}
	}
	return nil
}

func (_c *DiscoveredEntityCreate) sqlSave(ctx context.Context) (*DiscoveredEntity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DiscoveredEntityCreate) createSpec() (*DiscoveredEntity, *sqlgraph.CreateSpec) {
	var (
		_node = &DiscoveredEntity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(discoveredentity.Table, sqlgraph.NewFieldSpec(discoveredentity.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UniqueID(); ok {
		_spec.SetField(discoveredentity.FieldUniqueID, field.TypeString, value)
		_node.UniqueID = value
	}
	if value, ok := _c.mutation.TypeCategory(); ok {
		_spec.SetField(discoveredentity.FieldTypeCategory, field.TypeString, value)
		_node.TypeCategory = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(discoveredentity.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Properties(); ok {
		_spec.SetField(discoveredentity.FieldProperties, field.TypeJSON, value)
		_node.Properties = value
	}
	if value, ok := _c.mutation.Embedding(); ok {
		_spec.SetField(discoveredentity.FieldEmbedding, field.TypeJSON, value)
		_node.Embedding = value
	}
	if value, ok := _c.mutation.ConfidenceScore(); ok {
		_spec.SetField(discoveredentity.FieldConfidenceScore, field.TypeFloat64, value)
		_node.ConfidenceScore = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(discoveredentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// DiscoveredEntityCreateBulk is the builder for creating many DiscoveredEntity entities in bulk.
type DiscoveredEntityCreateBulk struct {
	config
	err      error
	builders []*DiscoveredEntityCreate
}

// Save creates the DiscoveredEntity entities in the database.
func (_c *DiscoveredEntityCreateBulk) Save(ctx context.Context) ([]*DiscoveredEntity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DiscoveredEntity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DiscoveredEntityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DiscoveredEntityCreateBulk) SaveX(ctx context.Context) []*DiscoveredEntity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DiscoveredEntityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DiscoveredEntityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
