// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Blogem/enron-graph/ent/discoveredentity"
)

// DiscoveredEntity is the model entity for the DiscoveredEntity schema.
type DiscoveredEntity struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Unique identifier (email, domain, etc.)
	UniqueID string `json:"unique_id,omitempty"`
	// Entity type: person, organization, concept, etc.
	TypeCategory string `json:"type_category,omitempty"`
	// Entity name or label
	Name string `json:"name,omitempty"`
	// Flexible properties stored as JSONB
	Properties map[string]interface{} `json:"properties,omitempty"`
	// Vector embedding (stored as JSON, used with pgvector)
	Embedding []float32 `json:"embedding,omitempty"`
	// Confidence score for entity extraction (0-1)
	ConfidenceScore float64 `json:"confidence_score,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DiscoveredEntity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case discoveredentity.FieldProperties, discoveredentity.FieldEmbedding:
			values[i] = new([]byte)
		case discoveredentity.FieldConfidenceScore:
			values[i] = new(sql.NullFloat64)
		case discoveredentity.FieldID:
			values[i] = new(sql.NullInt64)
		case discoveredentity.FieldUniqueID, discoveredentity.FieldTypeCategory, discoveredentity.FieldName:
			values[i] = new(sql.NullString)
		case discoveredentity.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DiscoveredEntity fields.
func (_m *DiscoveredEntity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case discoveredentity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case discoveredentity.FieldUniqueID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unique_id", values[i])
			} else if value.Valid {
				_m.UniqueID = value.String
			}
		case discoveredentity.FieldTypeCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type_category", values[i])
			} else if value.Valid {
				_m.TypeCategory = value.String
			}
		case discoveredentity.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case discoveredentity.FieldProperties:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field properties", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Properties); err != nil {
					return fmt.Errorf("unmarshal field properties: %w", err)
				}
			}
		case discoveredentity.FieldEmbedding:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field embedding", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Embedding); err != nil {
					return fmt.Errorf("unmarshal field embedding: %w", err)
				}
			}
		case discoveredentity.FieldConfidenceScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence_score", values[i])
			} else if value.Valid {
				_m.ConfidenceScore = value.Float64
			}
		case discoveredentity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DiscoveredEntity.
// This includes values selected through modifiers, order, etc.
func (_m *DiscoveredEntity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DiscoveredEntity.
// Note that you need to call DiscoveredEntity.Unwrap() before calling this method if this DiscoveredEntity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DiscoveredEntity) Update() *DiscoveredEntityUpdateOne {
	return NewDiscoveredEntityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DiscoveredEntity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DiscoveredEntity) Unwrap() *DiscoveredEntity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DiscoveredEntity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DiscoveredEntity) String() string {
	var builder strings.Builder
	builder.WriteString("DiscoveredEntity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("unique_id=")
	builder.WriteString(_m.UniqueID)
	builder.WriteString(", ")
	builder.WriteString("type_category=")
	builder.WriteString(_m.TypeCategory)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("properties=")
	builder.WriteString(fmt.Sprintf("%v", _m.Properties))
	builder.WriteString(", ")
	builder.WriteString("embedding=")
	builder.WriteString(fmt.Sprintf("%v", _m.Embedding))
	builder.WriteString(", ")
	builder.WriteString("confidence_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfidenceScore))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DiscoveredEntities is a parsable slice of DiscoveredEntity.
type DiscoveredEntities []*DiscoveredEntity
