// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Blogem/enron-graph/ent/email"
	"github.com/Blogem/enron-graph/ent/predicate"
)

// EmailUpdate is the builder for updating Email entities.
type EmailUpdate struct {
	config
	hooks    []Hook
	mutation *EmailMutation
}

// Where appends a list predicates to the EmailUpdate builder.
func (_u *EmailUpdate) Where(ps ...predicate.Email) *EmailUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *EmailUpdate) SetMessageID(v string) *EmailUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *EmailUpdate) SetNillableMessageID(v *string) *EmailUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetFrom sets the "from" field.
func (_u *EmailUpdate) SetFrom(v string) *EmailUpdate {
	_u.mutation.SetFrom(v)
	return _u
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (_u *EmailUpdate) SetNillableFrom(v *string) *EmailUpdate {
	if v != nil {
		_u.SetFrom(*v)
	}
	return _u
}

// SetTo sets the "to" field.
func (_u *EmailUpdate) SetTo(v []string) *EmailUpdate {
	_u.mutation.SetTo(v)
	return _u
}

// AppendTo appends value to the "to" field.
func (_u *EmailUpdate) AppendTo(v []string) *EmailUpdate {
	_u.mutation.AppendTo(v)
	return _u
}

// ClearTo clears the value of the "to" field.
func (_u *EmailUpdate) ClearTo() *EmailUpdate {
	_u.mutation.ClearTo()
	return _u
}

// SetCc sets the "cc" field.
func (_u *EmailUpdate) SetCc(v []string) *EmailUpdate {
	_u.mutation.SetCc(v)
	return _u
}

// AppendCc appends value to the "cc" field.
func (_u *EmailUpdate) AppendCc(v []string) *EmailUpdate {
	_u.mutation.AppendCc(v)
	return _u
}

// ClearCc clears the value of the "cc" field.
func (_u *EmailUpdate) ClearCc() *EmailUpdate {
	_u.mutation.ClearCc()
	return _u
}

// SetBcc sets the "bcc" field.
func (_u *EmailUpdate) SetBcc(v []string) *EmailUpdate {
	_u.mutation.SetBcc(v)
	return _u
}

// AppendBcc appends value to the "bcc" field.
func (_u *EmailUpdate) AppendBcc(v []string) *EmailUpdate {
	_u.mutation.AppendBcc(v)
	return _u
}

// ClearBcc clears the value of the "bcc" field.
func (_u *EmailUpdate) ClearBcc() *EmailUpdate {
	_u.mutation.ClearBcc()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *EmailUpdate) SetSubject(v string) *EmailUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *EmailUpdate) SetNillableSubject(v *string) *EmailUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *EmailUpdate) SetDate(v time.Time) *EmailUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *EmailUpdate) SetNillableDate(v *time.Time) *EmailUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *EmailUpdate) SetBody(v string) *EmailUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *EmailUpdate) SetNillableBody(v *string) *EmailUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *EmailUpdate) SetFilePath(v string) *EmailUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *EmailUpdate) SetNillableFilePath(v *string) *EmailUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// ClearFilePath clears the value of the "file_path" field.
func (_u *EmailUpdate) ClearFilePath() *EmailUpdate {
	_u.mutation.ClearFilePath()
	return _u
}

// Mutation returns the EmailMutation object of the builder.
func (_u *EmailUpdate) Mutation() *EmailMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailUpdate) check() error {
	if v, ok := _u.mutation.MessageID(); ok {
		if err := email.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "Email.message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.From(); ok {
		if err := email.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf(`ent: validator failed for field "Email.from": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(email.Table, email.Columns, sqlgraph.NewFieldSpec(email.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(email.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.From(); ok {
		_spec.SetField(email.FieldFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.To(); ok {
		_spec.SetField(email.FieldTo, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTo(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, email.FieldTo, value)
		})
	}
	if _u.mutation.ToCleared() {
		_spec.ClearField(email.FieldTo, field.TypeJSON)
	}
	if value, ok := _u.mutation.Cc(); ok {
		_spec.SetField(email.FieldCc, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCc(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, email.FieldCc, value)
		})
	}
	if _u.mutation.CcCleared() {
		_spec.ClearField(email.FieldCc, field.TypeJSON)
	}
	if value, ok := _u.mutation.Bcc(); ok {
		_spec.SetField(email.FieldBcc, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBcc(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, email.FieldBcc, value)
		})
	}
	if _u.mutation.BccCleared() {
		_spec.ClearField(email.FieldBcc, field.TypeJSON)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(email.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(email.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(email.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(email.FieldFilePath, field.TypeString, value)
	}
	if _u.mutation.FilePathCleared() {
		_spec.ClearField(email.FieldFilePath, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{email.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailUpdateOne is the builder for updating a single Email entity.
type EmailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailMutation
}

// SetMessageID sets the "message_id" field.
func (_u *EmailUpdateOne) SetMessageID(v string) *EmailUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *EmailUpdateOne) SetNillableMessageID(v *string) *EmailUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetFrom sets the "from" field.
func (_u *EmailUpdateOne) SetFrom(v string) *EmailUpdateOne {
	_u.mutation.SetFrom(v)
	return _u
}

// SetNillableFrom sets the "from" field if the given value is not nil.
func (_u *EmailUpdateOne) SetNillableFrom(v *string) *EmailUpdateOne {
	if v != nil {
		_u.SetFrom(*v)
	}
	return _u
}

// SetTo sets the "to" field.
func (_u *EmailUpdateOne) SetTo(v []string) *EmailUpdateOne {
	_u.mutation.SetTo(v)
	return _u
}

// AppendTo appends value to the "to" field.
func (_u *EmailUpdateOne) AppendTo(v []string) *EmailUpdateOne {
	_u.mutation.AppendTo(v)
	return _u
}

// ClearTo clears the value of the "to" field.
func (_u *EmailUpdateOne) ClearTo() *EmailUpdateOne {
	_u.mutation.ClearTo()
	return _u
}

// SetCc sets the "cc" field.
func (_u *EmailUpdateOne) SetCc(v []string) *EmailUpdateOne {
	_u.mutation.SetCc(v)
	return _u
}

// AppendCc appends value to the "cc" field.
func (_u *EmailUpdateOne) AppendCc(v []string) *EmailUpdateOne {
	_u.mutation.AppendCc(v)
	return _u
}

// ClearCc clears the value of the "cc" field.
func (_u *EmailUpdateOne) ClearCc() *EmailUpdateOne {
	_u.mutation.ClearCc()
	return _u
}

// SetBcc sets the "bcc" field.
func (_u *EmailUpdateOne) SetBcc(v []string) *EmailUpdateOne {
	_u.mutation.SetBcc(v)
	return _u
}

// AppendBcc appends value to the "bcc" field.
func (_u *EmailUpdateOne) AppendBcc(v []string) *EmailUpdateOne {
	_u.mutation.AppendBcc(v)
	return _u
}

// ClearBcc clears the value of the "bcc" field.
func (_u *EmailUpdateOne) ClearBcc() *EmailUpdateOne {
	_u.mutation.ClearBcc()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *EmailUpdateOne) SetSubject(v string) *EmailUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *EmailUpdateOne) SetNillableSubject(v *string) *EmailUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *EmailUpdateOne) SetDate(v time.Time) *EmailUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *EmailUpdateOne) SetNillableDate(v *time.Time) *EmailUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *EmailUpdateOne) SetBody(v string) *EmailUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *EmailUpdateOne) SetNillableBody(v *string) *EmailUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *EmailUpdateOne) SetFilePath(v string) *EmailUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *EmailUpdateOne) SetNillableFilePath(v *string) *EmailUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// ClearFilePath clears the value of the "file_path" field.
func (_u *EmailUpdateOne) ClearFilePath() *EmailUpdateOne {
	_u.mutation.ClearFilePath()
	return _u
}

// Mutation returns the EmailMutation object of the builder.
func (_u *EmailUpdateOne) Mutation() *EmailMutation {
	return _u.mutation
}

// Where appends a list predicates to the EmailUpdate builder.
func (_u *EmailUpdateOne) Where(ps ...predicate.Email) *EmailUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailUpdateOne) Select(field string, fields ...string) *EmailUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Email entity.
func (_u *EmailUpdateOne) Save(ctx context.Context) (*Email, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailUpdateOne) SaveX(ctx context.Context) *Email {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailUpdateOne) check() error {
	if v, ok := _u.mutation.MessageID(); ok {
		if err := email.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "Email.message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.From(); ok {
		if err := email.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf(`ent: validator failed for field "Email.from": %w`, err)}
		}
	}
	return nil
}

func (_u *EmailUpdateOne) sqlSave(ctx context.Context) (_node *Email, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(email.Table, email.Columns, sqlgraph.NewFieldSpec(email.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Email.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, email.FieldID)
		for _, f := range fields {
			if !email.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != email.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(email.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.From(); ok {
		_spec.SetField(email.FieldFrom, field.TypeString, value)
	}
	if value, ok := _u.mutation.To(); ok {
		_spec.SetField(email.FieldTo, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTo(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, email.FieldTo, value)
		})
	}
	if _u.mutation.ToCleared() {
		_spec.ClearField(email.FieldTo, field.TypeJSON)
	}
	if value, ok := _u.mutation.Cc(); ok {
		_spec.SetField(email.FieldCc, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCc(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, email.FieldCc, value)
		})
	}
	if _u.mutation.CcCleared() {
		_spec.ClearField(email.FieldCc, field.TypeJSON)
	}
	if value, ok := _u.mutation.Bcc(); ok {
		_spec.SetField(email.FieldBcc, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBcc(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, email.FieldBcc, value)
		})
	}
	if _u.mutation.BccCleared() {
		_spec.ClearField(email.FieldBcc, field.TypeJSON)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(email.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(email.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(email.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(email.FieldFilePath, field.TypeString, value)
	}
	if _u.mutation.FilePathCleared() {
		_spec.ClearField(email.FieldFilePath, field.TypeString)
	}
	_node = &Email{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{email.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
