// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blogem/enron-graph/ent/email"
)

// EmailCreate is the builder for creating a Email entity.
type EmailCreate struct {
	config
	mutation *EmailMutation
	hooks    []Hook
}

// SetMessageID sets the "message_id" field.
func (_c *EmailCreate) SetMessageID(v string) *EmailCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetFrom sets the "from" field.
func (_c *EmailCreate) SetFrom(v string) *EmailCreate {
	_c.mutation.SetFrom(v)
	return _c
}

// SetTo sets the "to" field.
func (_c *EmailCreate) SetTo(v []string) *EmailCreate {
	_c.mutation.SetTo(v)
	return _c
}

// SetCc sets the "cc" field.
func (_c *EmailCreate) SetCc(v []string) *EmailCreate {
	_c.mutation.SetCc(v)
	return _c
}

// SetBcc sets the "bcc" field.
func (_c *EmailCreate) SetBcc(v []string) *EmailCreate {
	_c.mutation.SetBcc(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *EmailCreate) SetSubject(v string) *EmailCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_c *EmailCreate) SetNillableSubject(v *string) *EmailCreate {
	if v != nil {
		_c.SetSubject(*v)
	}
	return _c
}

// SetDate sets the "date" field.
func (_c *EmailCreate) SetDate(v time.Time) *EmailCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_c *EmailCreate) SetNillableDate(v *time.Time) *EmailCreate {
	if v != nil {
		_c.SetDate(*v)
	}
	return _c
}

// SetBody sets the "body" field.
func (_c *EmailCreate) SetBody(v string) *EmailCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_c *EmailCreate) SetNillableBody(v *string) *EmailCreate {
	if v != nil {
		_c.SetBody(*v)
	}
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *EmailCreate) SetFilePath(v string) *EmailCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_c *EmailCreate) SetNillableFilePath(v *string) *EmailCreate {
	if v != nil {
		_c.SetFilePath(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EmailCreate) SetCreatedAt(v time.Time) *EmailCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EmailCreate) SetNillableCreatedAt(v *time.Time) *EmailCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the EmailMutation object of the builder.
func (_c *EmailCreate) Mutation() *EmailMutation {
	return _c.mutation
}

// Save creates the Email in the database.
func (_c *EmailCreate) Save(ctx context.Context) (*Email, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EmailCreate) SaveX(ctx context.Context) *Email {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EmailCreate) defaults() {
	if _, ok := _c.mutation.Subject(); !ok {
		v := email.DefaultSubject
		_c.mutation.SetSubject(v)
	}
	if _, ok := _c.mutation.Date(); !ok {
		v := email.DefaultDate()
		_c.mutation.SetDate(v)
	}
	if _, ok := _c.mutation.Body(); !ok {
		v := email.DefaultBody
		_c.mutation.SetBody(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := email.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EmailCreate) check() error {
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "Email.message_id"`)}
	}
	if v, ok := _c.mutation.MessageID(); ok {
		if err := email.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "Email.message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.From(); !ok {
		return &ValidationError{Name: "from", err: errors.New(`ent: missing required field "Email.from"`)}
	}
	if v, ok := _c.mutation.From(); ok {
		if err := email.FromValidator(v); err != nil {
			return &ValidationError{Name: "from", err: fmt.Errorf(`ent: validator failed for field "Email.from": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "Email.subject"`)}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Email.date"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "Email.body"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Email.created_at"`)}
	}
	return nil
}

func (_c *EmailCreate) sqlSave(ctx context.Context) (*Email, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EmailCreate) createSpec() (*Email, *sqlgraph.CreateSpec) {
	var (
		_node = &Email{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(email.Table, sqlgraph.NewFieldSpec(email.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(email.FieldMessageID, field.TypeString, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.From(); ok {
		_spec.SetField(email.FieldFrom, field.TypeString, value)
		_node.From = value
	}
	if value, ok := _c.mutation.To(); ok {
		_spec.SetField(email.FieldTo, field.TypeJSON, value)
		_node.To = value
	}
	if value, ok := _c.mutation.Cc(); ok {
		_spec.SetField(email.FieldCc, field.TypeJSON, value)
		_node.Cc = value
	}
	if value, ok := _c.mutation.Bcc(); ok {
		_spec.SetField(email.FieldBcc, field.TypeJSON, value)
		_node.Bcc = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(email.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(email.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(email.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(email.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(email.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// EmailCreateBulk is the builder for creating many Email entities in bulk.
type EmailCreateBulk struct {
	config
	err      error
	builders []*EmailCreate
}

// Save creates the Email entities in the database.
func (_c *EmailCreateBulk) Save(ctx context.Context) ([]*Email, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Email, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EmailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EmailCreateBulk) SaveX(ctx context.Context) []*Email {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EmailCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EmailCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
