// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blogem/enron-graph/ent/relationship"
)

// RelationshipCreate is the builder for creating a Relationship entity.
type RelationshipCreate struct {
	config
	mutation *RelationshipMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *RelationshipCreate) SetType(v string) *RelationshipCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetFromType sets the "from_type" field.
func (_c *RelationshipCreate) SetFromType(v string) *RelationshipCreate {
	_c.mutation.SetFromType(v)
	return _c
}

// SetFromID sets the "from_id" field.
func (_c *RelationshipCreate) SetFromID(v int) *RelationshipCreate {
	_c.mutation.SetFromID(v)
	return _c
}

// SetToType sets the "to_type" field.
func (_c *RelationshipCreate) SetToType(v string) *RelationshipCreate {
	_c.mutation.SetToType(v)
	return _c
}

// SetToID sets the "to_id" field.
func (_c *RelationshipCreate) SetToID(v int) *RelationshipCreate {
	_c.mutation.SetToID(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *RelationshipCreate) SetTimestamp(v time.Time) *RelationshipCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *RelationshipCreate) SetNillableTimestamp(v *time.Time) *RelationshipCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetConfidenceScore sets the "confidence_score" field.
func (_c *RelationshipCreate) SetConfidenceScore(v float64) *RelationshipCreate {
	_c.mutation.SetConfidenceScore(v)
	return _c
}

// SetNillableConfidenceScore sets the "confidence_score" field if the given value is not nil.
func (_c *RelationshipCreate) SetNillableConfidenceScore(v *float64) *RelationshipCreate {
	if v != nil {
		_c.SetConfidenceScore(*v)
	}
	return _c
}

// SetProperties sets the "properties" field.
func (_c *RelationshipCreate) SetProperties(v map[string]interface{}) *RelationshipCreate {
	_c.mutation.SetProperties(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RelationshipCreate) SetCreatedAt(v time.Time) *RelationshipCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RelationshipCreate) SetNillableCreatedAt(v *time.Time) *RelationshipCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the RelationshipMutation object of the builder.
func (_c *RelationshipCreate) Mutation() *RelationshipMutation {
	return _c.mutation
}

// Save creates the Relationship in the database.
func (_c *RelationshipCreate) Save(ctx context.Context) (*Relationship, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RelationshipCreate) SaveX(ctx context.Context) *Relationship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelationshipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelationshipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RelationshipCreate) defaults() {
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := relationship.DefaultTimestamp()
		_c.mutation.SetTimestamp(v)
	}
	if _, ok := _c.mutation.ConfidenceScore(); !ok {
		v := relationship.DefaultConfidenceScore
		_c.mutation.SetConfidenceScore(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := relationship.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RelationshipCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Relationship.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := relationship.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Relationship.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromType(); !ok {
		return &ValidationError{Name: "from_type", err: errors.New(`ent: missing required field "Relationship.from_type"`)}
	}
	if v, ok := _c.mutation.FromType(); ok {
		if err := relationship.FromTypeValidator(v); err != nil {
			return &ValidationError{Name: "from_type", err: fmt.Errorf(`ent: validator failed for field "Relationship.from_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromID(); !ok {
		return &ValidationError{Name: "from_id", err: errors.New(`ent: missing required field "Relationship.from_id"`)}
	}
	if v, ok := _c.mutation.FromID(); ok {
		if err := relationship.FromIDValidator(v); err != nil {
			return &ValidationError{Name: "from_id", err: fmt.Errorf(`ent: validator failed for field "Relationship.from_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToType(); !ok {
		return &ValidationError{Name: "to_type", err: errors.New(`ent: missing required field "Relationship.to_type"`)}
	}
	if v, ok := _c.mutation.ToType(); ok {
		if err := relationship.ToTypeValidator(v); err != nil {
			return &ValidationError{Name: "to_type", err: fmt.Errorf(`ent: validator failed for field "Relationship.to_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ToID(); !ok {
		return &ValidationError{Name: "to_id", err: errors.New(`ent: missing required field "Relationship.to_id"`)}
	}
	if v, ok := _c.mutation.ToID(); ok {
		if err := relationship.ToIDValidator(v); err != nil {
			return &ValidationError{Name: "to_id", err: fmt.Errorf(`ent: validator failed for field "Relationship.to_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "Relationship.timestamp"`)}
	}
	if _, ok := _c.mutation.ConfidenceScore(); !ok {
		return &ValidationError{Name: "confidence_score", err: errors.New(`ent: missing required field "Relationship.confidence_score"`)}
	}
	if v, ok := _c.mutation.ConfidenceScore(); ok {
		if err := relationship.ConfidenceScoreValidator(v); err != nil {
			return &ValidationError{Name: "confidence_score", err: fmt.Errorf(`ent: validator failed for field "Relationship.confidence_score": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Relationship.created_at"`)}
	}
	return nil
}

func (_c *RelationshipCreate) sqlSave(ctx context.Context) (*Relationship, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RelationshipCreate) createSpec() (*Relationship, *sqlgraph.CreateSpec) {
	var (
		_node = &Relationship{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(relationship.Table, sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(relationship.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.FromType(); ok {
		_spec.SetField(relationship.FieldFromType, field.TypeString, value)
		_node.FromType = value
	}
	if value, ok := _c.mutation.FromID(); ok {
		_spec.SetField(relationship.FieldFromID, field.TypeInt, value)
		_node.FromID = value
	}
	if value, ok := _c.mutation.ToType(); ok {
		_spec.SetField(relationship.FieldToType, field.TypeString, value)
		_node.ToType = value
	}
	if value, ok := _c.mutation.ToID(); ok {
		_spec.SetField(relationship.FieldToID, field.TypeInt, value)
		_node.ToID = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(relationship.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.ConfidenceScore(); ok {
		_spec.SetField(relationship.FieldConfidenceScore, field.TypeFloat64, value)
		_node.ConfidenceScore = value
	}
	if value, ok := _c.mutation.Properties(); ok {
		_spec.SetField(relationship.FieldProperties, field.TypeJSON, value)
		_node.Properties = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(relationship.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RelationshipCreateBulk is the builder for creating many Relationship entities in bulk.
type RelationshipCreateBulk struct {
	config
	err      error
	builders []*RelationshipCreate
}

// Save creates the Relationship entities in the database.
func (_c *RelationshipCreateBulk) Save(ctx context.Context) ([]*Relationship, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Relationship, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelationshipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RelationshipCreateBulk) SaveX(ctx context.Context) []*Relationship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RelationshipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RelationshipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
