// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Blogem/enron-graph/ent/relationship"
)

// Relationship is the model entity for the Relationship schema.
type Relationship struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Relationship type: SENT, RECEIVED, MENTIONS, COMMUNICATES_WITH
	Type string `json:"type,omitempty"`
	// Source entity type: email, discovered_entity, person, etc.
	FromType string `json:"from_type,omitempty"`
	// Source entity ID
	FromID int `json:"from_id,omitempty"`
	// Target entity type
	ToType string `json:"to_type,omitempty"`
	// Target entity ID
	ToID int `json:"to_id,omitempty"`
	// When the relationship occurred or was created
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Confidence score for relationship (0-1)
	ConfidenceScore float64 `json:"confidence_score,omitempty"`
	// Additional metadata as JSONB
	Properties map[string]interface{} `json:"properties,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Relationship) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case relationship.FieldProperties:
			values[i] = new([]byte)
		case relationship.FieldConfidenceScore:
			values[i] = new(sql.NullFloat64)
		case relationship.FieldID, relationship.FieldFromID, relationship.FieldToID:
			values[i] = new(sql.NullInt64)
		case relationship.FieldType, relationship.FieldFromType, relationship.FieldToType:
			values[i] = new(sql.NullString)
		case relationship.FieldTimestamp, relationship.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Relationship fields.
func (_m *Relationship) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case relationship.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case relationship.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case relationship.FieldFromType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_type", values[i])
			} else if value.Valid {
				_m.FromType = value.String
			}
		case relationship.FieldFromID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field from_id", values[i])
			} else if value.Valid {
				_m.FromID = int(value.Int64)
			}
		case relationship.FieldToType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field to_type", values[i])
			} else if value.Valid {
				_m.ToType = value.String
			}
		case relationship.FieldToID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field to_id", values[i])
			} else if value.Valid {
				_m.ToID = int(value.Int64)
			}
		case relationship.FieldTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[i])
			} else if value.Valid {
				_m.Timestamp = value.Time
			}
		case relationship.FieldConfidenceScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence_score", values[i])
			} else if value.Valid {
				_m.ConfidenceScore = value.Float64
			}
		case relationship.FieldProperties:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field properties", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Properties); err != nil {
					return fmt.Errorf("unmarshal field properties: %w", err)
				}
			}
		case relationship.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Relationship.
// This includes values selected through modifiers, order, etc.
func (_m *Relationship) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Relationship.
// Note that you need to call Relationship.Unwrap() before calling this method if this Relationship
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Relationship) Update() *RelationshipUpdateOne {
	return NewRelationshipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Relationship entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Relationship) Unwrap() *Relationship {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Relationship is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Relationship) String() string {
	var builder strings.Builder
	builder.WriteString("Relationship(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("from_type=")
	builder.WriteString(_m.FromType)
	builder.WriteString(", ")
	builder.WriteString("from_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FromID))
	builder.WriteString(", ")
	builder.WriteString("to_type=")
	builder.WriteString(_m.ToType)
	builder.WriteString(", ")
	builder.WriteString("to_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToID))
	builder.WriteString(", ")
	builder.WriteString("timestamp=")
	builder.WriteString(_m.Timestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("confidence_score=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfidenceScore))
	builder.WriteString(", ")
	builder.WriteString("properties=")
	builder.WriteString(fmt.Sprintf("%v", _m.Properties))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Relationships is a parsable slice of Relationship.
type Relationships []*Relationship
