// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blogem/enron-graph/ent/predicate"
	"github.com/Blogem/enron-graph/ent/relationship"
)

// RelationshipUpdate is the builder for updating Relationship entities.
type RelationshipUpdate struct {
	config
	hooks    []Hook
	mutation *RelationshipMutation
}

// Where appends a list predicates to the RelationshipUpdate builder.
func (_u *RelationshipUpdate) Where(ps ...predicate.Relationship) *RelationshipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *RelationshipUpdate) SetType(v string) *RelationshipUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableType(v *string) *RelationshipUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetFromType sets the "from_type" field.
func (_u *RelationshipUpdate) SetFromType(v string) *RelationshipUpdate {
	_u.mutation.SetFromType(v)
	return _u
}

// SetNillableFromType sets the "from_type" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableFromType(v *string) *RelationshipUpdate {
	if v != nil {
		_u.SetFromType(*v)
	}
	return _u
}

// SetFromID sets the "from_id" field.
func (_u *RelationshipUpdate) SetFromID(v int) *RelationshipUpdate {
	_u.mutation.ResetFromID()
	_u.mutation.SetFromID(v)
	return _u
}

// SetNillableFromID sets the "from_id" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableFromID(v *int) *RelationshipUpdate {
	if v != nil {
		_u.SetFromID(*v)
	}
	return _u
}

// AddFromID adds value to the "from_id" field.
func (_u *RelationshipUpdate) AddFromID(v int) *RelationshipUpdate {
	_u.mutation.AddFromID(v)
	return _u
}

// SetToType sets the "to_type" field.
func (_u *RelationshipUpdate) SetToType(v string) *RelationshipUpdate {
	_u.mutation.SetToType(v)
	return _u
}

// SetNillableToType sets the "to_type" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableToType(v *string) *RelationshipUpdate {
	if v != nil {
		_u.SetToType(*v)
	}
	return _u
}

// SetToID sets the "to_id" field.
func (_u *RelationshipUpdate) SetToID(v int) *RelationshipUpdate {
	_u.mutation.ResetToID()
	_u.mutation.SetToID(v)
	return _u
}

// SetNillableToID sets the "to_id" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableToID(v *int) *RelationshipUpdate {
	if v != nil {
		_u.SetToID(*v)
	}
	return _u
}

// AddToID adds value to the "to_id" field.
func (_u *RelationshipUpdate) AddToID(v int) *RelationshipUpdate {
	_u.mutation.AddToID(v)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *RelationshipUpdate) SetTimestamp(v time.Time) *RelationshipUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableTimestamp(v *time.Time) *RelationshipUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetConfidenceScore sets the "confidence_score" field.
func (_u *RelationshipUpdate) SetConfidenceScore(v float64) *RelationshipUpdate {
	_u.mutation.ResetConfidenceScore()
	_u.mutation.SetConfidenceScore(v)
	return _u
}

// SetNillableConfidenceScore sets the "confidence_score" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableConfidenceScore(v *float64) *RelationshipUpdate {
	if v != nil {
		_u.SetConfidenceScore(*v)
	}
	return _u
}

// AddConfidenceScore adds value to the "confidence_score" field.
func (_u *RelationshipUpdate) AddConfidenceScore(v float64) *RelationshipUpdate {
	_u.mutation.AddConfidenceScore(v)
	return _u
}

// SetProperties sets the "properties" field.
func (_u *RelationshipUpdate) SetProperties(v map[string]interface{}) *RelationshipUpdate {
	_u.mutation.SetProperties(v)
	return _u
}

// ClearProperties clears the value of the "properties" field.
func (_u *RelationshipUpdate) ClearProperties() *RelationshipUpdate {
	_u.mutation.ClearProperties()
	return _u
}

// Mutation returns the RelationshipMutation object of the builder.
func (_u *RelationshipUpdate) Mutation() *RelationshipMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelationshipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelationshipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelationshipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelationshipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelationshipUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := relationship.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Relationship.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromType(); ok {
		if err := relationship.FromTypeValidator(v); err != nil {
			return &ValidationError{Name: "from_type", err: fmt.Errorf(`ent: validator failed for field "Relationship.from_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromID(); ok {
		if err := relationship.FromIDValidator(v); err != nil {
			return &ValidationError{Name: "from_id", err: fmt.Errorf(`ent: validator failed for field "Relationship.from_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToType(); ok {
		if err := relationship.ToTypeValidator(v); err != nil {
			return &ValidationError{Name: "to_type", err: fmt.Errorf(`ent: validator failed for field "Relationship.to_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToID(); ok {
		if err := relationship.ToIDValidator(v); err != nil {
			return &ValidationError{Name: "to_id", err: fmt.Errorf(`ent: validator failed for field "Relationship.to_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfidenceScore(); ok {
		if err := relationship.ConfidenceScoreValidator(v); err != nil {
			return &ValidationError{Name: "confidence_score", err: fmt.Errorf(`ent: validator failed for field "Relationship.confidence_score": %w`, err)}
		}
	}
	return nil
}

func (_u *RelationshipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relationship.Table, relationship.Columns, sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(relationship.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromType(); ok {
		_spec.SetField(relationship.FieldFromType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromID(); ok {
		_spec.SetField(relationship.FieldFromID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFromID(); ok {
		_spec.AddField(relationship.FieldFromID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ToType(); ok {
		_spec.SetField(relationship.FieldToType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToID(); ok {
		_spec.SetField(relationship.FieldToID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedToID(); ok {
		_spec.AddField(relationship.FieldToID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(relationship.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConfidenceScore(); ok {
		_spec.SetField(relationship.FieldConfidenceScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidenceScore(); ok {
		_spec.AddField(relationship.FieldConfidenceScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Properties(); ok {
		_spec.SetField(relationship.FieldProperties, field.TypeJSON, value)
	}
	if _u.mutation.PropertiesCleared() {
		_spec.ClearField(relationship.FieldProperties, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relationship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelationshipUpdateOne is the builder for updating a single Relationship entity.
type RelationshipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelationshipMutation
}

// SetType sets the "type" field.
func (_u *RelationshipUpdateOne) SetType(v string) *RelationshipUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableType(v *string) *RelationshipUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetFromType sets the "from_type" field.
func (_u *RelationshipUpdateOne) SetFromType(v string) *RelationshipUpdateOne {
	_u.mutation.SetFromType(v)
	return _u
}

// SetNillableFromType sets the "from_type" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableFromType(v *string) *RelationshipUpdateOne {
	if v != nil {
		_u.SetFromType(*v)
	}
	return _u
}

// SetFromID sets the "from_id" field.
func (_u *RelationshipUpdateOne) SetFromID(v int) *RelationshipUpdateOne {
	_u.mutation.ResetFromID()
	_u.mutation.SetFromID(v)
	return _u
}

// SetNillableFromID sets the "from_id" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableFromID(v *int) *RelationshipUpdateOne {
	if v != nil {
		_u.SetFromID(*v)
	}
	return _u
}

// AddFromID adds value to the "from_id" field.
func (_u *RelationshipUpdateOne) AddFromID(v int) *RelationshipUpdateOne {
	_u.mutation.AddFromID(v)
	return _u
}

// SetToType sets the "to_type" field.
func (_u *RelationshipUpdateOne) SetToType(v string) *RelationshipUpdateOne {
	_u.mutation.SetToType(v)
	return _u
}

// SetNillableToType sets the "to_type" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableToType(v *string) *RelationshipUpdateOne {
	if v != nil {
		_u.SetToType(*v)
	}
	return _u
}

// SetToID sets the "to_id" field.
func (_u *RelationshipUpdateOne) SetToID(v int) *RelationshipUpdateOne {
	_u.mutation.ResetToID()
	_u.mutation.SetToID(v)
	return _u
}

// SetNillableToID sets the "to_id" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableToID(v *int) *RelationshipUpdateOne {
	if v != nil {
		_u.SetToID(*v)
	}
	return _u
}

// AddToID adds value to the "to_id" field.
func (_u *RelationshipUpdateOne) AddToID(v int) *RelationshipUpdateOne {
	_u.mutation.AddToID(v)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *RelationshipUpdateOne) SetTimestamp(v time.Time) *RelationshipUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableTimestamp(v *time.Time) *RelationshipUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetConfidenceScore sets the "confidence_score" field.
func (_u *RelationshipUpdateOne) SetConfidenceScore(v float64) *RelationshipUpdateOne {
	_u.mutation.ResetConfidenceScore()
	_u.mutation.SetConfidenceScore(v)
	return _u
}

// SetNillableConfidenceScore sets the "confidence_score" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableConfidenceScore(v *float64) *RelationshipUpdateOne {
	if v != nil {
		_u.SetConfidenceScore(*v)
	}
	return _u
}

// AddConfidenceScore adds value to the "confidence_score" field.
func (_u *RelationshipUpdateOne) AddConfidenceScore(v float64) *RelationshipUpdateOne {
	_u.mutation.AddConfidenceScore(v)
	return _u
}

// SetProperties sets the "properties" field.
func (_u *RelationshipUpdateOne) SetProperties(v map[string]interface{}) *RelationshipUpdateOne {
	_u.mutation.SetProperties(v)
	return _u
}

// ClearProperties clears the value of the "properties" field.
func (_u *RelationshipUpdateOne) ClearProperties() *RelationshipUpdateOne {
	_u.mutation.ClearProperties()
	return _u
}

// Mutation returns the RelationshipMutation object of the builder.
func (_u *RelationshipUpdateOne) Mutation() *RelationshipMutation {
	return _u.mutation
}

// Where appends a list predicates to the RelationshipUpdate builder.
func (_u *RelationshipUpdateOne) Where(ps ...predicate.Relationship) *RelationshipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelationshipUpdateOne) Select(field string, fields ...string) *RelationshipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Relationship entity.
func (_u *RelationshipUpdateOne) Save(ctx context.Context) (*Relationship, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelationshipUpdateOne) SaveX(ctx context.Context) *Relationship {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelationshipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelationshipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelationshipUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := relationship.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Relationship.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromType(); ok {
		if err := relationship.FromTypeValidator(v); err != nil {
			return &ValidationError{Name: "from_type", err: fmt.Errorf(`ent: validator failed for field "Relationship.from_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromID(); ok {
		if err := relationship.FromIDValidator(v); err != nil {
			return &ValidationError{Name: "from_id", err: fmt.Errorf(`ent: validator failed for field "Relationship.from_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToType(); ok {
		if err := relationship.ToTypeValidator(v); err != nil {
			return &ValidationError{Name: "to_type", err: fmt.Errorf(`ent: validator failed for field "Relationship.to_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToID(); ok {
		if err := relationship.ToIDValidator(v); err != nil {
			return &ValidationError{Name: "to_id", err: fmt.Errorf(`ent: validator failed for field "Relationship.to_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfidenceScore(); ok {
		if err := relationship.ConfidenceScoreValidator(v); err != nil {
			return &ValidationError{Name: "confidence_score", err: fmt.Errorf(`ent: validator failed for field "Relationship.confidence_score": %w`, err)}
		}
	}
	return nil
}

func (_u *RelationshipUpdateOne) sqlSave(ctx context.Context) (_node *Relationship, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relationship.Table, relationship.Columns, sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Relationship.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relationship.FieldID)
		for _, f := range fields {
			if !relationship.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relationship.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(relationship.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromType(); ok {
		_spec.SetField(relationship.FieldFromType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromID(); ok {
		_spec.SetField(relationship.FieldFromID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFromID(); ok {
		_spec.AddField(relationship.FieldFromID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ToType(); ok {
		_spec.SetField(relationship.FieldToType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToID(); ok {
		_spec.SetField(relationship.FieldToID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedToID(); ok {
		_spec.AddField(relationship.FieldToID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(relationship.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConfidenceScore(); ok {
		_spec.SetField(relationship.FieldConfidenceScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidenceScore(); ok {
		_spec.AddField(relationship.FieldConfidenceScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Properties(); ok {
		_spec.SetField(relationship.FieldProperties, field.TypeJSON, value)
	}
	if _u.mutation.PropertiesCleared() {
		_spec.ClearField(relationship.FieldProperties, field.TypeJSON)
	}
	_node = &Relationship{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relationship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
