// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Blogem/enron-graph/ent/discoveredentity"
	"github.com/Blogem/enron-graph/ent/email"
	"github.com/Blogem/enron-graph/ent/relationship"
	"github.com/Blogem/enron-graph/ent/schema"
	"github.com/Blogem/enron-graph/ent/schemapromotion"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	discoveredentityFields := schema.DiscoveredEntity{}.Fields()
	_ = discoveredentityFields
	// discoveredentityDescUniqueID is the schema descriptor for unique_id field.
	discoveredentityDescUniqueID := discoveredentityFields[0].Descriptor()
	// discoveredentity.UniqueIDValidator is a validator for the "unique_id" field. It is called by the builders before save.
	discoveredentity.UniqueIDValidator = discoveredentityDescUniqueID.Validators[0].(func(string) error)
	// discoveredentityDescTypeCategory is the schema descriptor for type_category field.
	discoveredentityDescTypeCategory := discoveredentityFields[1].Descriptor()
	// discoveredentity.TypeCategoryValidator is a validator for the "type_category" field. It is called by the builders before save.
	discoveredentity.TypeCategoryValidator = discoveredentityDescTypeCategory.Validators[0].(func(string) error)
	// discoveredentityDescName is the schema descriptor for name field.
	discoveredentityDescName := discoveredentityFields[2].Descriptor()
	// discoveredentity.NameValidator is a validator for the "name" field. It is called by the builders before save.
	discoveredentity.NameValidator = discoveredentityDescName.Validators[0].(func(string) error)
	// discoveredentityDescConfidenceScore is the schema descriptor for confidence_score field.
	discoveredentityDescConfidenceScore := discoveredentityFields[5].Descriptor()
	// discoveredentity.DefaultConfidenceScore holds the default value on creation for the confidence_score field.
	discoveredentity.DefaultConfidenceScore = discoveredentityDescConfidenceScore.Default.(float64)
	// discoveredentity.ConfidenceScoreValidator is a validator for the "confidence_score" field. It is called by the builders before save.
	discoveredentity.ConfidenceScoreValidator = func() func(float64) error {
		validators := discoveredentityDescConfidenceScore.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(confidence_score float64) error {
			for _, fn := range fns {
				if err := fn(confidence_score); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// discoveredentityDescCreatedAt is the schema descriptor for created_at field.
	discoveredentityDescCreatedAt := discoveredentityFields[6].Descriptor()
	// discoveredentity.DefaultCreatedAt holds the default value on creation for the created_at field.
	discoveredentity.DefaultCreatedAt = discoveredentityDescCreatedAt.Default.(func() time.Time)
	emailFields := schema.Email{}.Fields()
	_ = emailFields
	// emailDescMessageID is the schema descriptor for message_id field.
	emailDescMessageID := emailFields[0].Descriptor()
	// email.MessageIDValidator is a validator for the "message_id" field. It is called by the builders before save.
	email.MessageIDValidator = emailDescMessageID.Validators[0].(func(string) error)
	// emailDescFrom is the schema descriptor for from field.
	emailDescFrom := emailFields[1].Descriptor()
	// email.FromValidator is a validator for the "from" field. It is called by the builders before save.
	email.FromValidator = emailDescFrom.Validators[0].(func(string) error)
	// emailDescSubject is the schema descriptor for subject field.
	emailDescSubject := emailFields[5].Descriptor()
	// email.DefaultSubject holds the default value on creation for the subject field.
	email.DefaultSubject = emailDescSubject.Default.(string)
	// emailDescDate is the schema descriptor for date field.
	emailDescDate := emailFields[6].Descriptor()
	// email.DefaultDate holds the default value on creation for the date field.
	email.DefaultDate = emailDescDate.Default.(func() time.Time)
	// emailDescBody is the schema descriptor for body field.
	emailDescBody := emailFields[7].Descriptor()
	// email.DefaultBody holds the default value on creation for the body field.
	email.DefaultBody = emailDescBody.Default.(string)
	// emailDescCreatedAt is the schema descriptor for created_at field.
	emailDescCreatedAt := emailFields[9].Descriptor()
	// email.DefaultCreatedAt holds the default value on creation for the created_at field.
	email.DefaultCreatedAt = emailDescCreatedAt.Default.(func() time.Time)
	relationshipFields := schema.Relationship{}.Fields()
	_ = relationshipFields
	// relationshipDescType is the schema descriptor for type field.
	relationshipDescType := relationshipFields[0].Descriptor()
	// relationship.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	relationship.TypeValidator = relationshipDescType.Validators[0].(func(string) error)
	// relationshipDescFromType is the schema descriptor for from_type field.
	relationshipDescFromType := relationshipFields[1].Descriptor()
	// relationship.FromTypeValidator is a validator for the "from_type" field. It is called by the builders before save.
	relationship.FromTypeValidator = relationshipDescFromType.Validators[0].(func(string) error)
	// relationshipDescFromID is the schema descriptor for from_id field.
	relationshipDescFromID := relationshipFields[2].Descriptor()
	// relationship.FromIDValidator is a validator for the "from_id" field. It is called by the builders before save.
	relationship.FromIDValidator = relationshipDescFromID.Validators[0].(func(int) error)
	// relationshipDescToType is the schema descriptor for to_type field.
	relationshipDescToType := relationshipFields[3].Descriptor()
	// relationship.ToTypeValidator is a validator for the "to_type" field. It is called by the builders before save.
	relationship.ToTypeValidator = relationshipDescToType.Validators[0].(func(string) error)
	// relationshipDescToID is the schema descriptor for to_id field.
	relationshipDescToID := relationshipFields[4].Descriptor()
	// relationship.ToIDValidator is a validator for the "to_id" field. It is called by the builders before save.
	relationship.ToIDValidator = relationshipDescToID.Validators[0].(func(int) error)
	// relationshipDescTimestamp is the schema descriptor for timestamp field.
	relationshipDescTimestamp := relationshipFields[5].Descriptor()
	// relationship.DefaultTimestamp holds the default value on creation for the timestamp field.
	relationship.DefaultTimestamp = relationshipDescTimestamp.Default.(func() time.Time)
	// relationshipDescConfidenceScore is the schema descriptor for confidence_score field.
	relationshipDescConfidenceScore := relationshipFields[6].Descriptor()
	// relationship.DefaultConfidenceScore holds the default value on creation for the confidence_score field.
	relationship.DefaultConfidenceScore = relationshipDescConfidenceScore.Default.(float64)
	// relationship.ConfidenceScoreValidator is a validator for the "confidence_score" field. It is called by the builders before save.
	relationship.ConfidenceScoreValidator = func() func(float64) error {
		validators := relationshipDescConfidenceScore.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(confidence_score float64) error {
			for _, fn := range fns {
				if err := fn(confidence_score); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// relationshipDescCreatedAt is the schema descriptor for created_at field.
	relationshipDescCreatedAt := relationshipFields[8].Descriptor()
	// relationship.DefaultCreatedAt holds the default value on creation for the created_at field.
	relationship.DefaultCreatedAt = relationshipDescCreatedAt.Default.(func() time.Time)
	schemapromotionFields := schema.SchemaPromotion{}.Fields()
	_ = schemapromotionFields
	// schemapromotionDescTypeName is the schema descriptor for type_name field.
	schemapromotionDescTypeName := schemapromotionFields[0].Descriptor()
	// schemapromotion.TypeNameValidator is a validator for the "type_name" field. It is called by the builders before save.
	schemapromotion.TypeNameValidator = schemapromotionDescTypeName.Validators[0].(func(string) error)
	// schemapromotionDescPromotedAt is the schema descriptor for promoted_at field.
	schemapromotionDescPromotedAt := schemapromotionFields[1].Descriptor()
	// schemapromotion.DefaultPromotedAt holds the default value on creation for the promoted_at field.
	schemapromotion.DefaultPromotedAt = schemapromotionDescPromotedAt.Default.(func() time.Time)
	// schemapromotionDescEntitiesAffected is the schema descriptor for entities_affected field.
	schemapromotionDescEntitiesAffected := schemapromotionFields[3].Descriptor()
	// schemapromotion.DefaultEntitiesAffected holds the default value on creation for the entities_affected field.
	schemapromotion.DefaultEntitiesAffected = schemapromotionDescEntitiesAffected.Default.(int)
	// schemapromotion.EntitiesAffectedValidator is a validator for the "entities_affected" field. It is called by the builders before save.
	schemapromotion.EntitiesAffectedValidator = schemapromotionDescEntitiesAffected.Validators[0].(func(int) error)
	// schemapromotionDescValidationFailures is the schema descriptor for validation_failures field.
	schemapromotionDescValidationFailures := schemapromotionFields[4].Descriptor()
	// schemapromotion.DefaultValidationFailures holds the default value on creation for the validation_failures field.
	schemapromotion.DefaultValidationFailures = schemapromotionDescValidationFailures.Default.(int)
	// schemapromotion.ValidationFailuresValidator is a validator for the "validation_failures" field. It is called by the builders before save.
	schemapromotion.ValidationFailuresValidator = schemapromotionDescValidationFailures.Validators[0].(func(int) error)
}
