// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Blogem/enron-graph/ent/schemapromotion"
)

// SchemaPromotion is the model entity for the SchemaPromotion schema.
type SchemaPromotion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name of the promoted type (e.g., Person, Organization)
	TypeName string `json:"type_name,omitempty"`
	// When the type was promoted to core schema
	PromotedAt time.Time `json:"promoted_at,omitempty"`
	// Criteria used for promotion: frequency, density, consistency
	PromotionCriteria map[string]interface{} `json:"promotion_criteria,omitempty"`
	// Number of entities migrated to new type
	EntitiesAffected int `json:"entities_affected,omitempty"`
	// Number of entities that failed validation
	ValidationFailures int `json:"validation_failures,omitempty"`
	// Generated schema definition rules
	SchemaDefinition map[string]interface{} `json:"schema_definition,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SchemaPromotion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schemapromotion.FieldPromotionCriteria, schemapromotion.FieldSchemaDefinition:
			values[i] = new([]byte)
		case schemapromotion.FieldID, schemapromotion.FieldEntitiesAffected, schemapromotion.FieldValidationFailures:
			values[i] = new(sql.NullInt64)
		case schemapromotion.FieldTypeName:
			values[i] = new(sql.NullString)
		case schemapromotion.FieldPromotedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SchemaPromotion fields.
func (_m *SchemaPromotion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schemapromotion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case schemapromotion.FieldTypeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type_name", values[i])
			} else if value.Valid {
				_m.TypeName = value.String
			}
		case schemapromotion.FieldPromotedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field promoted_at", values[i])
			} else if value.Valid {
				_m.PromotedAt = value.Time
			}
		case schemapromotion.FieldPromotionCriteria:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field promotion_criteria", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PromotionCriteria); err != nil {
					return fmt.Errorf("unmarshal field promotion_criteria: %w", err)
				}
			}
		case schemapromotion.FieldEntitiesAffected:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entities_affected", values[i])
			} else if value.Valid {
				_m.EntitiesAffected = int(value.Int64)
			}
		case schemapromotion.FieldValidationFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validation_failures", values[i])
			} else if value.Valid {
				_m.ValidationFailures = int(value.Int64)
			}
		case schemapromotion.FieldSchemaDefinition:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field schema_definition", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SchemaDefinition); err != nil {
					return fmt.Errorf("unmarshal field schema_definition: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SchemaPromotion.
// This includes values selected through modifiers, order, etc.
func (_m *SchemaPromotion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SchemaPromotion.
// Note that you need to call SchemaPromotion.Unwrap() before calling this method if this SchemaPromotion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SchemaPromotion) Update() *SchemaPromotionUpdateOne {
	return NewSchemaPromotionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SchemaPromotion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SchemaPromotion) Unwrap() *SchemaPromotion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SchemaPromotion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SchemaPromotion) String() string {
	var builder strings.Builder
	builder.WriteString("SchemaPromotion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type_name=")
	builder.WriteString(_m.TypeName)
	builder.WriteString(", ")
	builder.WriteString("promoted_at=")
	builder.WriteString(_m.PromotedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("promotion_criteria=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromotionCriteria))
	builder.WriteString(", ")
	builder.WriteString("entities_affected=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntitiesAffected))
	builder.WriteString(", ")
	builder.WriteString("validation_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidationFailures))
	builder.WriteString(", ")
	builder.WriteString("schema_definition=")
	builder.WriteString(fmt.Sprintf("%v", _m.SchemaDefinition))
	builder.WriteByte(')')
	return builder.String()
}

// SchemaPromotions is a parsable slice of SchemaPromotion.
type SchemaPromotions []*SchemaPromotion
