// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blogem/enron-graph/ent/predicate"
	"github.com/Blogem/enron-graph/ent/schemapromotion"
)

// SchemaPromotionUpdate is the builder for updating SchemaPromotion entities.
type SchemaPromotionUpdate struct {
	config
	hooks    []Hook
	mutation *SchemaPromotionMutation
}

// Where appends a list predicates to the SchemaPromotionUpdate builder.
func (_u *SchemaPromotionUpdate) Where(ps ...predicate.SchemaPromotion) *SchemaPromotionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTypeName sets the "type_name" field.
func (_u *SchemaPromotionUpdate) SetTypeName(v string) *SchemaPromotionUpdate {
	_u.mutation.SetTypeName(v)
	return _u
}

// SetNillableTypeName sets the "type_name" field if the given value is not nil.
func (_u *SchemaPromotionUpdate) SetNillableTypeName(v *string) *SchemaPromotionUpdate {
	if v != nil {
		_u.SetTypeName(*v)
	}
	return _u
}

// SetPromotedAt sets the "promoted_at" field.
func (_u *SchemaPromotionUpdate) SetPromotedAt(v time.Time) *SchemaPromotionUpdate {
	_u.mutation.SetPromotedAt(v)
	return _u
}

// SetNillablePromotedAt sets the "promoted_at" field if the given value is not nil.
func (_u *SchemaPromotionUpdate) SetNillablePromotedAt(v *time.Time) *SchemaPromotionUpdate {
	if v != nil {
		_u.SetPromotedAt(*v)
	}
	return _u
}

// SetPromotionCriteria sets the "promotion_criteria" field.
func (_u *SchemaPromotionUpdate) SetPromotionCriteria(v map[string]interface{}) *SchemaPromotionUpdate {
	_u.mutation.SetPromotionCriteria(v)
	return _u
}

// ClearPromotionCriteria clears the value of the "promotion_criteria" field.
func (_u *SchemaPromotionUpdate) ClearPromotionCriteria() *SchemaPromotionUpdate {
	_u.mutation.ClearPromotionCriteria()
	return _u
}

// SetEntitiesAffected sets the "entities_affected" field.
func (_u *SchemaPromotionUpdate) SetEntitiesAffected(v int) *SchemaPromotionUpdate {
	_u.mutation.ResetEntitiesAffected()
	_u.mutation.SetEntitiesAffected(v)
	return _u
}

// SetNillableEntitiesAffected sets the "entities_affected" field if the given value is not nil.
func (_u *SchemaPromotionUpdate) SetNillableEntitiesAffected(v *int) *SchemaPromotionUpdate {
	if v != nil {
		_u.SetEntitiesAffected(*v)
	}
	return _u
}

// AddEntitiesAffected adds value to the "entities_affected" field.
func (_u *SchemaPromotionUpdate) AddEntitiesAffected(v int) *SchemaPromotionUpdate {
	_u.mutation.AddEntitiesAffected(v)
	return _u
}

// SetValidationFailures sets the "validation_failures" field.
func (_u *SchemaPromotionUpdate) SetValidationFailures(v int) *SchemaPromotionUpdate {
	_u.mutation.ResetValidationFailures()
	_u.mutation.SetValidationFailures(v)
	return _u
}

// SetNillableValidationFailures sets the "validation_failures" field if the given value is not nil.
func (_u *SchemaPromotionUpdate) SetNillableValidationFailures(v *int) *SchemaPromotionUpdate {
	if v != nil {
		_u.SetValidationFailures(*v)
	}
	return _u
}

// AddValidationFailures adds value to the "validation_failures" field.
func (_u *SchemaPromotionUpdate) AddValidationFailures(v int) *SchemaPromotionUpdate {
	_u.mutation.AddValidationFailures(v)
	return _u
}

// SetSchemaDefinition sets the "schema_definition" field.
func (_u *SchemaPromotionUpdate) SetSchemaDefinition(v map[string]interface{}) *SchemaPromotionUpdate {
	_u.mutation.SetSchemaDefinition(v)
	return _u
}

// ClearSchemaDefinition clears the value of the "schema_definition" field.
func (_u *SchemaPromotionUpdate) ClearSchemaDefinition() *SchemaPromotionUpdate {
	_u.mutation.ClearSchemaDefinition()
	return _u
}

// Mutation returns the SchemaPromotionMutation object of the builder.
func (_u *SchemaPromotionUpdate) Mutation() *SchemaPromotionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SchemaPromotionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchemaPromotionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SchemaPromotionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchemaPromotionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchemaPromotionUpdate) check() error {
	if v, ok := _u.mutation.TypeName(); ok {
		if err := schemapromotion.TypeNameValidator(v); err != nil {
			return &ValidationError{Name: "type_name", err: fmt.Errorf(`ent: validator failed for field "SchemaPromotion.type_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntitiesAffected(); ok {
		if err := schemapromotion.EntitiesAffectedValidator(v); err != nil {
			return &ValidationError{Name: "entities_affected", err: fmt.Errorf(`ent: validator failed for field "SchemaPromotion.entities_affected": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidationFailures(); ok {
		if err := schemapromotion.ValidationFailuresValidator(v); err != nil {
			return &ValidationError{Name: "validation_failures", err: fmt.Errorf(`ent: validator failed for field "SchemaPromotion.validation_failures": %w`, err)}
		}
	}
	return nil
}

func (_u *SchemaPromotionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schemapromotion.Table, schemapromotion.Columns, sqlgraph.NewFieldSpec(schemapromotion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TypeName(); ok {
		_spec.SetField(schemapromotion.FieldTypeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromotedAt(); ok {
		_spec.SetField(schemapromotion.FieldPromotedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PromotionCriteria(); ok {
		_spec.SetField(schemapromotion.FieldPromotionCriteria, field.TypeJSON, value)
	}
	if _u.mutation.PromotionCriteriaCleared() {
		_spec.ClearField(schemapromotion.FieldPromotionCriteria, field.TypeJSON)
	}
	if value, ok := _u.mutation.EntitiesAffected(); ok {
		_spec.SetField(schemapromotion.FieldEntitiesAffected, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntitiesAffected(); ok {
		_spec.AddField(schemapromotion.FieldEntitiesAffected, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidationFailures(); ok {
		_spec.SetField(schemapromotion.FieldValidationFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidationFailures(); ok {
		_spec.AddField(schemapromotion.FieldValidationFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SchemaDefinition(); ok {
		_spec.SetField(schemapromotion.FieldSchemaDefinition, field.TypeJSON, value)
	}
	if _u.mutation.SchemaDefinitionCleared() {
		_spec.ClearField(schemapromotion.FieldSchemaDefinition, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemapromotion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SchemaPromotionUpdateOne is the builder for updating a single SchemaPromotion entity.
type SchemaPromotionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SchemaPromotionMutation
}

// SetTypeName sets the "type_name" field.
func (_u *SchemaPromotionUpdateOne) SetTypeName(v string) *SchemaPromotionUpdateOne {
	_u.mutation.SetTypeName(v)
	return _u
}

// SetNillableTypeName sets the "type_name" field if the given value is not nil.
func (_u *SchemaPromotionUpdateOne) SetNillableTypeName(v *string) *SchemaPromotionUpdateOne {
	if v != nil {
		_u.SetTypeName(*v)
	}
	return _u
}

// SetPromotedAt sets the "promoted_at" field.
func (_u *SchemaPromotionUpdateOne) SetPromotedAt(v time.Time) *SchemaPromotionUpdateOne {
	_u.mutation.SetPromotedAt(v)
	return _u
}

// SetNillablePromotedAt sets the "promoted_at" field if the given value is not nil.
func (_u *SchemaPromotionUpdateOne) SetNillablePromotedAt(v *time.Time) *SchemaPromotionUpdateOne {
	if v != nil {
		_u.SetPromotedAt(*v)
	}
	return _u
}

// SetPromotionCriteria sets the "promotion_criteria" field.
func (_u *SchemaPromotionUpdateOne) SetPromotionCriteria(v map[string]interface{}) *SchemaPromotionUpdateOne {
	_u.mutation.SetPromotionCriteria(v)
	return _u
}

// ClearPromotionCriteria clears the value of the "promotion_criteria" field.
func (_u *SchemaPromotionUpdateOne) ClearPromotionCriteria() *SchemaPromotionUpdateOne {
	_u.mutation.ClearPromotionCriteria()
	return _u
}

// SetEntitiesAffected sets the "entities_affected" field.
func (_u *SchemaPromotionUpdateOne) SetEntitiesAffected(v int) *SchemaPromotionUpdateOne {
	_u.mutation.ResetEntitiesAffected()
	_u.mutation.SetEntitiesAffected(v)
	return _u
}

// SetNillableEntitiesAffected sets the "entities_affected" field if the given value is not nil.
func (_u *SchemaPromotionUpdateOne) SetNillableEntitiesAffected(v *int) *SchemaPromotionUpdateOne {
	if v != nil {
		_u.SetEntitiesAffected(*v)
	}
	return _u
}

// AddEntitiesAffected adds value to the "entities_affected" field.
func (_u *SchemaPromotionUpdateOne) AddEntitiesAffected(v int) *SchemaPromotionUpdateOne {
	_u.mutation.AddEntitiesAffected(v)
	return _u
}

// SetValidationFailures sets the "validation_failures" field.
func (_u *SchemaPromotionUpdateOne) SetValidationFailures(v int) *SchemaPromotionUpdateOne {
	_u.mutation.ResetValidationFailures()
	_u.mutation.SetValidationFailures(v)
	return _u
}

// SetNillableValidationFailures sets the "validation_failures" field if the given value is not nil.
func (_u *SchemaPromotionUpdateOne) SetNillableValidationFailures(v *int) *SchemaPromotionUpdateOne {
	if v != nil {
		_u.SetValidationFailures(*v)
	}
	return _u
}

// AddValidationFailures adds value to the "validation_failures" field.
func (_u *SchemaPromotionUpdateOne) AddValidationFailures(v int) *SchemaPromotionUpdateOne {
	_u.mutation.AddValidationFailures(v)
	return _u
}

// SetSchemaDefinition sets the "schema_definition" field.
func (_u *SchemaPromotionUpdateOne) SetSchemaDefinition(v map[string]interface{}) *SchemaPromotionUpdateOne {
	_u.mutation.SetSchemaDefinition(v)
	return _u
}

// ClearSchemaDefinition clears the value of the "schema_definition" field.
func (_u *SchemaPromotionUpdateOne) ClearSchemaDefinition() *SchemaPromotionUpdateOne {
	_u.mutation.ClearSchemaDefinition()
	return _u
}

// Mutation returns the SchemaPromotionMutation object of the builder.
func (_u *SchemaPromotionUpdateOne) Mutation() *SchemaPromotionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SchemaPromotionUpdate builder.
func (_u *SchemaPromotionUpdateOne) Where(ps ...predicate.SchemaPromotion) *SchemaPromotionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SchemaPromotionUpdateOne) Select(field string, fields ...string) *SchemaPromotionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SchemaPromotion entity.
func (_u *SchemaPromotionUpdateOne) Save(ctx context.Context) (*SchemaPromotion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SchemaPromotionUpdateOne) SaveX(ctx context.Context) *SchemaPromotion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SchemaPromotionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SchemaPromotionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SchemaPromotionUpdateOne) check() error {
	if v, ok := _u.mutation.TypeName(); ok {
		if err := schemapromotion.TypeNameValidator(v); err != nil {
			return &ValidationError{Name: "type_name", err: fmt.Errorf(`ent: validator failed for field "SchemaPromotion.type_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntitiesAffected(); ok {
		if err := schemapromotion.EntitiesAffectedValidator(v); err != nil {
			return &ValidationError{Name: "entities_affected", err: fmt.Errorf(`ent: validator failed for field "SchemaPromotion.entities_affected": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ValidationFailures(); ok {
		if err := schemapromotion.ValidationFailuresValidator(v); err != nil {
			return &ValidationError{Name: "validation_failures", err: fmt.Errorf(`ent: validator failed for field "SchemaPromotion.validation_failures": %w`, err)}
		}
	}
	return nil
}

func (_u *SchemaPromotionUpdateOne) sqlSave(ctx context.Context) (_node *SchemaPromotion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(schemapromotion.Table, schemapromotion.Columns, sqlgraph.NewFieldSpec(schemapromotion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SchemaPromotion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schemapromotion.FieldID)
		for _, f := range fields {
			if !schemapromotion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != schemapromotion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TypeName(); ok {
		_spec.SetField(schemapromotion.FieldTypeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PromotedAt(); ok {
		_spec.SetField(schemapromotion.FieldPromotedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PromotionCriteria(); ok {
		_spec.SetField(schemapromotion.FieldPromotionCriteria, field.TypeJSON, value)
	}
	if _u.mutation.PromotionCriteriaCleared() {
		_spec.ClearField(schemapromotion.FieldPromotionCriteria, field.TypeJSON)
	}
	if value, ok := _u.mutation.EntitiesAffected(); ok {
		_spec.SetField(schemapromotion.FieldEntitiesAffected, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEntitiesAffected(); ok {
		_spec.AddField(schemapromotion.FieldEntitiesAffected, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidationFailures(); ok {
		_spec.SetField(schemapromotion.FieldValidationFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidationFailures(); ok {
		_spec.AddField(schemapromotion.FieldValidationFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SchemaDefinition(); ok {
		_spec.SetField(schemapromotion.FieldSchemaDefinition, field.TypeJSON, value)
	}
	if _u.mutation.SchemaDefinitionCleared() {
		_spec.ClearField(schemapromotion.FieldSchemaDefinition, field.TypeJSON)
	}
	_node = &SchemaPromotion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{schemapromotion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
