// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Blogem/enron-graph/ent/schemapromotion"
)

// SchemaPromotionCreate is the builder for creating a SchemaPromotion entity.
type SchemaPromotionCreate struct {
	config
	mutation *SchemaPromotionMutation
	hooks    []Hook
}

// SetTypeName sets the "type_name" field.
func (_c *SchemaPromotionCreate) SetTypeName(v string) *SchemaPromotionCreate {
	_c.mutation.SetTypeName(v)
	return _c
}

// SetPromotedAt sets the "promoted_at" field.
func (_c *SchemaPromotionCreate) SetPromotedAt(v time.Time) *SchemaPromotionCreate {
	_c.mutation.SetPromotedAt(v)
	return _c
}

// SetNillablePromotedAt sets the "promoted_at" field if the given value is not nil.
func (_c *SchemaPromotionCreate) SetNillablePromotedAt(v *time.Time) *SchemaPromotionCreate {
	if v != nil {
		_c.SetPromotedAt(*v)
	}
	return _c
}

// SetPromotionCriteria sets the "promotion_criteria" field.
func (_c *SchemaPromotionCreate) SetPromotionCriteria(v map[string]interface{}) *SchemaPromotionCreate {
	_c.mutation.SetPromotionCriteria(v)
	return _c
}

// SetEntitiesAffected sets the "entities_affected" field.
func (_c *SchemaPromotionCreate) SetEntitiesAffected(v int) *SchemaPromotionCreate {
	_c.mutation.SetEntitiesAffected(v)
	return _c
}

// SetNillableEntitiesAffected sets the "entities_affected" field if the given value is not nil.
func (_c *SchemaPromotionCreate) SetNillableEntitiesAffected(v *int) *SchemaPromotionCreate {
	if v != nil {
		_c.SetEntitiesAffected(*v)
	}
	return _c
}

// SetValidationFailures sets the "validation_failures" field.
func (_c *SchemaPromotionCreate) SetValidationFailures(v int) *SchemaPromotionCreate {
	_c.mutation.SetValidationFailures(v)
	return _c
}

// SetNillableValidationFailures sets the "validation_failures" field if the given value is not nil.
func (_c *SchemaPromotionCreate) SetNillableValidationFailures(v *int) *SchemaPromotionCreate {
	if v != nil {
		_c.SetValidationFailures(*v)
	}
	return _c
}

// SetSchemaDefinition sets the "schema_definition" field.
func (_c *SchemaPromotionCreate) SetSchemaDefinition(v map[string]interface{}) *SchemaPromotionCreate {
	_c.mutation.SetSchemaDefinition(v)
	return _c
}

// Mutation returns the SchemaPromotionMutation object of the builder.
func (_c *SchemaPromotionCreate) Mutation() *SchemaPromotionMutation {
	return _c.mutation
}

// Save creates the SchemaPromotion in the database.
func (_c *SchemaPromotionCreate) Save(ctx context.Context) (*SchemaPromotion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SchemaPromotionCreate) SaveX(ctx context.Context) *SchemaPromotion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchemaPromotionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchemaPromotionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SchemaPromotionCreate) defaults() {
	if _, ok := _c.mutation.PromotedAt(); !ok {
		v := schemapromotion.DefaultPromotedAt()
		_c.mutation.SetPromotedAt(v)
	}
	if _, ok := _c.mutation.EntitiesAffected(); !ok {
		v := schemapromotion.DefaultEntitiesAffected
		_c.mutation.SetEntitiesAffected(v)
	}
	if _, ok := _c.mutation.ValidationFailures(); !ok {
		v := schemapromotion.DefaultValidationFailures
		_c.mutation.SetValidationFailures(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SchemaPromotionCreate) check() error {
	if _, ok := _c.mutation.TypeName(); !ok {
		return &ValidationError{Name: "type_name", err: errors.New(`ent: missing required field "SchemaPromotion.type_name"`)}
	}
	if v, ok := _c.mutation.TypeName(); ok {
		if err := schemapromotion.TypeNameValidator(v); err != nil {
			return &ValidationError{Name: "type_name", err: fmt.Errorf(`ent: validator failed for field "SchemaPromotion.type_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PromotedAt(); !ok {
		return &ValidationError{Name: "promoted_at", err: errors.New(`ent: missing required field "SchemaPromotion.promoted_at"`)}
	}
	if _, ok := _c.mutation.EntitiesAffected(); !ok {
		return &ValidationError{Name: "entities_affected", err: errors.New(`ent: missing required field "SchemaPromotion.entities_affected"`)}
	}
	if v, ok := _c.mutation.EntitiesAffected(); ok {
		if err := schemapromotion.EntitiesAffectedValidator(v); err != nil {
			return &ValidationError{Name: "entities_affected", err: fmt.Errorf(`ent: validator failed for field "SchemaPromotion.entities_affected": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValidationFailures(); !ok {
		return &ValidationError{Name: "validation_failures", err: errors.New(`ent: missing required field "SchemaPromotion.validation_failures"`)}
	}
	if v, ok := _c.mutation.ValidationFailures(); ok {
		if err := schemapromotion.ValidationFailuresValidator(v); err != nil {
			return &ValidationError{Name: "validation_failures", err: fmt.Errorf(`ent: validator failed for field "SchemaPromotion.validation_failures": %w`, err)}
		}
	}
	return nil
}

func (_c *SchemaPromotionCreate) sqlSave(ctx context.Context) (*SchemaPromotion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SchemaPromotionCreate) createSpec() (*SchemaPromotion, *sqlgraph.CreateSpec) {
	var (
		_node = &SchemaPromotion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(schemapromotion.Table, sqlgraph.NewFieldSpec(schemapromotion.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TypeName(); ok {
		_spec.SetField(schemapromotion.FieldTypeName, field.TypeString, value)
		_node.TypeName = value
	}
	if value, ok := _c.mutation.PromotedAt(); ok {
		_spec.SetField(schemapromotion.FieldPromotedAt, field.TypeTime, value)
		_node.PromotedAt = value
	}
	if value, ok := _c.mutation.PromotionCriteria(); ok {
		_spec.SetField(schemapromotion.FieldPromotionCriteria, field.TypeJSON, value)
		_node.PromotionCriteria = value
	}
	if value, ok := _c.mutation.EntitiesAffected(); ok {
		_spec.SetField(schemapromotion.FieldEntitiesAffected, field.TypeInt, value)
		_node.EntitiesAffected = value
	}
	if value, ok := _c.mutation.ValidationFailures(); ok {
		_spec.SetField(schemapromotion.FieldValidationFailures, field.TypeInt, value)
		_node.ValidationFailures = value
	}
	if value, ok := _c.mutation.SchemaDefinition(); ok {
		_spec.SetField(schemapromotion.FieldSchemaDefinition, field.TypeJSON, value)
		_node.SchemaDefinition = value
	}
	return _node, _spec
}

// SchemaPromotionCreateBulk is the builder for creating many SchemaPromotion entities in bulk.
type SchemaPromotionCreateBulk struct {
	config
	err      error
	builders []*SchemaPromotionCreate
}

// Save creates the SchemaPromotion entities in the database.
func (_c *SchemaPromotionCreateBulk) Save(ctx context.Context) ([]*SchemaPromotion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SchemaPromotion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SchemaPromotionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SchemaPromotionCreateBulk) SaveX(ctx context.Context) []*SchemaPromotion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SchemaPromotionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SchemaPromotionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
