// Code generated by ent, DO NOT EDIT.

package relationship

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the relationship type in the database.
	Label = "relationship"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldFromType holds the string denoting the from_type field in the database.
	FieldFromType = "from_type"
	// FieldFromID holds the string denoting the from_id field in the database.
	FieldFromID = "from_id"
	// FieldToType holds the string denoting the to_type field in the database.
	FieldToType = "to_type"
	// FieldToID holds the string denoting the to_id field in the database.
	FieldToID = "to_id"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldConfidenceScore holds the string denoting the confidence_score field in the database.
	FieldConfidenceScore = "confidence_score"
	// FieldProperties holds the string denoting the properties field in the database.
	FieldProperties = "properties"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the relationship in the database.
	Table = "relationships"
)

// Columns holds all SQL columns for relationship fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldFromType,
	FieldFromID,
	FieldToType,
	FieldToID,
	FieldTimestamp,
	FieldConfidenceScore,
	FieldProperties,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// FromTypeValidator is a validator for the "from_type" field. It is called by the builders before save.
	FromTypeValidator func(string) error
	// FromIDValidator is a validator for the "from_id" field. It is called by the builders before save.
	FromIDValidator func(int) error
	// ToTypeValidator is a validator for the "to_type" field. It is called by the builders before save.
	ToTypeValidator func(string) error
	// ToIDValidator is a validator for the "to_id" field. It is called by the builders before save.
	ToIDValidator func(int) error
	// DefaultTimestamp holds the default value on creation for the "timestamp" field.
	DefaultTimestamp func() time.Time
	// DefaultConfidenceScore holds the default value on creation for the "confidence_score" field.
	DefaultConfidenceScore float64
	// ConfidenceScoreValidator is a validator for the "confidence_score" field. It is called by the builders before save.
	ConfidenceScoreValidator func(float64) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Relationship queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByFromType orders the results by the from_type field.
func ByFromType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromType, opts...).ToFunc()
}

// ByFromID orders the results by the from_id field.
func ByFromID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromID, opts...).ToFunc()
}

// ByToType orders the results by the to_type field.
func ByToType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToType, opts...).ToFunc()
}

// ByToID orders the results by the to_id field.
func ByToID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToID, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByConfidenceScore orders the results by the confidence_score field.
func ByConfidenceScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidenceScore, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
