// Code generated by ent, DO NOT EDIT.

package relationship

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Blogem/enron-graph/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldType, v))
}

// FromType applies equality check predicate on the "from_type" field. It's identical to FromTypeEQ.
func FromType(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldFromType, v))
}

// FromID applies equality check predicate on the "from_id" field. It's identical to FromIDEQ.
func FromID(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldFromID, v))
}

// ToType applies equality check predicate on the "to_type" field. It's identical to ToTypeEQ.
func ToType(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldToType, v))
}

// ToID applies equality check predicate on the "to_id" field. It's identical to ToIDEQ.
func ToID(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldToID, v))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldTimestamp, v))
}

// ConfidenceScore applies equality check predicate on the "confidence_score" field. It's identical to ConfidenceScoreEQ.
func ConfidenceScore(v float64) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldConfidenceScore, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldCreatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldType, v))
}

// FromTypeEQ applies the EQ predicate on the "from_type" field.
func FromTypeEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldFromType, v))
}

// FromTypeNEQ applies the NEQ predicate on the "from_type" field.
func FromTypeNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldFromType, v))
}

// FromTypeIn applies the In predicate on the "from_type" field.
func FromTypeIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldFromType, vs...))
}

// FromTypeNotIn applies the NotIn predicate on the "from_type" field.
func FromTypeNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldFromType, vs...))
}

// FromTypeGT applies the GT predicate on the "from_type" field.
func FromTypeGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldFromType, v))
}

// FromTypeGTE applies the GTE predicate on the "from_type" field.
func FromTypeGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldFromType, v))
}

// FromTypeLT applies the LT predicate on the "from_type" field.
func FromTypeLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldFromType, v))
}

// FromTypeLTE applies the LTE predicate on the "from_type" field.
func FromTypeLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldFromType, v))
}

// FromTypeContains applies the Contains predicate on the "from_type" field.
func FromTypeContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldFromType, v))
}

// FromTypeHasPrefix applies the HasPrefix predicate on the "from_type" field.
func FromTypeHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldFromType, v))
}

// FromTypeHasSuffix applies the HasSuffix predicate on the "from_type" field.
func FromTypeHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldFromType, v))
}

// FromTypeEqualFold applies the EqualFold predicate on the "from_type" field.
func FromTypeEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldFromType, v))
}

// FromTypeContainsFold applies the ContainsFold predicate on the "from_type" field.
func FromTypeContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldFromType, v))
}

// FromIDEQ applies the EQ predicate on the "from_id" field.
func FromIDEQ(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldFromID, v))
}

// FromIDNEQ applies the NEQ predicate on the "from_id" field.
func FromIDNEQ(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldFromID, v))
}

// FromIDIn applies the In predicate on the "from_id" field.
func FromIDIn(vs ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldFromID, vs...))
}

// FromIDNotIn applies the NotIn predicate on the "from_id" field.
func FromIDNotIn(vs ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldFromID, vs...))
}

// FromIDGT applies the GT predicate on the "from_id" field.
func FromIDGT(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldFromID, v))
}

// FromIDGTE applies the GTE predicate on the "from_id" field.
func FromIDGTE(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldFromID, v))
}

// FromIDLT applies the LT predicate on the "from_id" field.
func FromIDLT(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldFromID, v))
}

// FromIDLTE applies the LTE predicate on the "from_id" field.
func FromIDLTE(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldFromID, v))
}

// ToTypeEQ applies the EQ predicate on the "to_type" field.
func ToTypeEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldToType, v))
}

// ToTypeNEQ applies the NEQ predicate on the "to_type" field.
func ToTypeNEQ(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldToType, v))
}

// ToTypeIn applies the In predicate on the "to_type" field.
func ToTypeIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldToType, vs...))
}

// ToTypeNotIn applies the NotIn predicate on the "to_type" field.
func ToTypeNotIn(vs ...string) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldToType, vs...))
}

// ToTypeGT applies the GT predicate on the "to_type" field.
func ToTypeGT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldToType, v))
}

// ToTypeGTE applies the GTE predicate on the "to_type" field.
func ToTypeGTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldToType, v))
}

// ToTypeLT applies the LT predicate on the "to_type" field.
func ToTypeLT(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldToType, v))
}

// ToTypeLTE applies the LTE predicate on the "to_type" field.
func ToTypeLTE(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldToType, v))
}

// ToTypeContains applies the Contains predicate on the "to_type" field.
func ToTypeContains(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContains(FieldToType, v))
}

// ToTypeHasPrefix applies the HasPrefix predicate on the "to_type" field.
func ToTypeHasPrefix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasPrefix(FieldToType, v))
}

// ToTypeHasSuffix applies the HasSuffix predicate on the "to_type" field.
func ToTypeHasSuffix(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldHasSuffix(FieldToType, v))
}

// ToTypeEqualFold applies the EqualFold predicate on the "to_type" field.
func ToTypeEqualFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldEqualFold(FieldToType, v))
}

// ToTypeContainsFold applies the ContainsFold predicate on the "to_type" field.
func ToTypeContainsFold(v string) predicate.Relationship {
	return predicate.Relationship(sql.FieldContainsFold(FieldToType, v))
}

// ToIDEQ applies the EQ predicate on the "to_id" field.
func ToIDEQ(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldToID, v))
}

// ToIDNEQ applies the NEQ predicate on the "to_id" field.
func ToIDNEQ(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldToID, v))
}

// ToIDIn applies the In predicate on the "to_id" field.
func ToIDIn(vs ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldToID, vs...))
}

// ToIDNotIn applies the NotIn predicate on the "to_id" field.
func ToIDNotIn(vs ...int) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldToID, vs...))
}

// ToIDGT applies the GT predicate on the "to_id" field.
func ToIDGT(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldToID, v))
}

// ToIDGTE applies the GTE predicate on the "to_id" field.
func ToIDGTE(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldToID, v))
}

// ToIDLT applies the LT predicate on the "to_id" field.
func ToIDLT(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldToID, v))
}

// ToIDLTE applies the LTE predicate on the "to_id" field.
func ToIDLTE(v int) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldToID, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldTimestamp, v))
}

// ConfidenceScoreEQ applies the EQ predicate on the "confidence_score" field.
func ConfidenceScoreEQ(v float64) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldConfidenceScore, v))
}

// ConfidenceScoreNEQ applies the NEQ predicate on the "confidence_score" field.
func ConfidenceScoreNEQ(v float64) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldConfidenceScore, v))
}

// ConfidenceScoreIn applies the In predicate on the "confidence_score" field.
func ConfidenceScoreIn(vs ...float64) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldConfidenceScore, vs...))
}

// ConfidenceScoreNotIn applies the NotIn predicate on the "confidence_score" field.
func ConfidenceScoreNotIn(vs ...float64) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldConfidenceScore, vs...))
}

// ConfidenceScoreGT applies the GT predicate on the "confidence_score" field.
func ConfidenceScoreGT(v float64) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldConfidenceScore, v))
}

// ConfidenceScoreGTE applies the GTE predicate on the "confidence_score" field.
func ConfidenceScoreGTE(v float64) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldConfidenceScore, v))
}

// ConfidenceScoreLT applies the LT predicate on the "confidence_score" field.
func ConfidenceScoreLT(v float64) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldConfidenceScore, v))
}

// ConfidenceScoreLTE applies the LTE predicate on the "confidence_score" field.
func ConfidenceScoreLTE(v float64) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldConfidenceScore, v))
}

// PropertiesIsNil applies the IsNil predicate on the "properties" field.
func PropertiesIsNil() predicate.Relationship {
	return predicate.Relationship(sql.FieldIsNull(FieldProperties))
}

// PropertiesNotNil applies the NotNil predicate on the "properties" field.
func PropertiesNotNil() predicate.Relationship {
	return predicate.Relationship(sql.FieldNotNull(FieldProperties))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Relationship {
	return predicate.Relationship(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Relationship) predicate.Relationship {
	return predicate.Relationship(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Relationship) predicate.Relationship {
	return predicate.Relationship(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Relationship) predicate.Relationship {
	return predicate.Relationship(sql.NotPredicates(p))
}
