// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DiscoveredEntity is the predicate function for discoveredentity builders.
type DiscoveredEntity func(*sql.Selector)

// Email is the predicate function for email builders.
type Email func(*sql.Selector)

// Relationship is the predicate function for relationship builders.
type Relationship func(*sql.Selector)

// SchemaPromotion is the predicate function for schemapromotion builders.
type SchemaPromotion func(*sql.Selector)
